/**
 * SCIQB - Mind Map Data & Dynamic Generator
 * Grounded in BHU UG NEP Syllabus
 */

const PREDEFINED_MINDMAPS = {
  "MATMJ51": {
    id: "MATMJ51",
    code: "MATMJ51",
    title: "Abstract Algebra",
    department: "Department of Mathematics",
    semester: 5,
    credits: 4,
    course_type: "Major",
    summary: "Comprehensive structure covering Group Theory, Isomorphism Theorems, Permutation Groups, Group Actions, Ring Theory, and Polynomial Algebras.",
    root: {
      id: "root",
      label: "Abstract Algebra",
      badge: "MATMJ51 • Sem 5",
      type: "root",
      details: "4 Credits Major Course. Foundations of Algebraic Structures.",
      children: [
        {
          id: "unit1",
          label: "Unit 1: Group Theory & Cosets",
          badge: "Unit 1",
          type: "unit",
          color: "#4F46E5", // Indigo
          details: "Homomorphisms, Isomorphisms, Subgroups, Cosets, and classical number theory applications of Lagrange's Theorem.",
          children: [
            {
              id: "u1_homo",
              label: "Homomorphism & Isomorphism",
              type: "topic",
              details: "Structure-preserving mappings between groups.",
              children: [
                { id: "u1_h1", label: "Homomorphism (φ(ab) = φ(a)φ(b))", type: "subtopic" },
                { id: "u1_h2", label: "Isomorphism (Bijective Homomorphism)", type: "subtopic" },
                { id: "u1_h3", label: "Kernel & Image Properties", type: "subtopic" }
              ]
            },
            {
              id: "u1_sub",
              label: "Subgroups & Generators",
              type: "topic",
              details: "Subgroup criteria and generators of groups.",
              children: [
                { id: "u1_s1", label: "Subgroup Test (H ≤ G)", type: "subtopic" },
                { id: "u1_s2", label: "Group Generated by a Subset ⟨S⟩", type: "subtopic" },
                { id: "u1_s3", label: "Center of a Group Z(G)", type: "subtopic" }
              ]
            },
            {
              id: "u1_coset",
              label: "Cosets & Lagrange Applications",
              type: "topic",
              details: "Partitioning groups and applying order relations.",
              children: [
                { id: "u1_c1", label: "Left & Right Cosets (aH / Ha)", type: "subtopic" },
                { id: "u1_c2", label: "Lagrange's Theorem (|H| divides |G|)", type: "subtopic" },
                { id: "u1_c3", label: "Euler's Totient Theorem", type: "subtopic" },
                { id: "u1_c4", label: "Fermat's Little Theorem", type: "subtopic" },
                { id: "u1_c5", label: "Wilson's Theorem", type: "subtopic" }
              ]
            }
          ]
        },
        {
          id: "unit2",
          label: "Unit 2: Isomorphism Theorems & Quotients",
          badge: "Unit 2",
          type: "unit",
          color: "#0891B2", // Cyan
          details: "Products of groups, normal subgroups, factor groups, fundamental isomorphism theorems, and commutators.",
          children: [
            {
              id: "u2_prod",
              label: "Product of Groups",
              type: "topic",
              details: "Combining groups via direct products.",
              children: [
                { id: "u2_p1", label: "External Direct Product (G × H)", type: "subtopic" },
                { id: "u2_p2", label: "Internal Direct Product", type: "subtopic" }
              ]
            },
            {
              id: "u2_normal",
              label: "Normal Subgroups & Quotient Groups",
              type: "topic",
              details: "Subgroups invariant under conjugation.",
              children: [
                { id: "u2_n1", label: "Normal Subgroup Criteria (gNg⁻¹ = N)", type: "subtopic" },
                { id: "u2_n2", label: "Quotient / Factor Group (G/N)", type: "subtopic" }
              ]
            },
            {
              id: "u2_theorems",
              label: "Isomorphism Theorems",
              type: "topic",
              details: "Core structural mapping theorems.",
              children: [
                { id: "u2_t1", label: "Fundamental Theorem of Homomorphism (G/Ker φ ≅ Im φ)", type: "subtopic" },
                { id: "u2_t2", label: "First Isomorphism Theorem", type: "subtopic" },
                { id: "u2_t3", label: "Second Isomorphism Theorem", type: "subtopic" }
              ]
            },
            {
              id: "u2_comm",
              label: "Commutator & Abelianization",
              type: "topic",
              details: "Measuring non-commutativity in groups.",
              children: [
                { id: "u2_cm1", label: "Commutator Element [g, h]", type: "subtopic" },
                { id: "u2_cm2", label: "Derived Subgroup G'", type: "subtopic" },
                { id: "u2_cm3", label: "Abelianization G/G'", type: "subtopic" }
              ]
            }
          ]
        },
        {
          id: "unit3",
          label: "Unit 3: Permutation & Symmetric Groups",
          badge: "Unit 3",
          type: "unit",
          color: "#D97706", // Amber
          details: "Symmetric groups Sn, cycle decompositions, transpositions, even/odd permutations, and alternating groups An.",
          children: [
            {
              id: "u3_sym",
              label: "Symmetric Group (Sₙ)",
              type: "topic",
              details: "Group of bijections on a set of n elements.",
              children: [
                { id: "u3_sm1", label: "Permutations & Notation", type: "subtopic" },
                { id: "u3_sm2", label: "Disjoint Cycle Decomposition", type: "subtopic" },
                { id: "u3_sm3", label: "Cycle Order & Length", type: "subtopic" }
              ]
            },
            {
              id: "u3_trans",
              label: "Transpositions & Parity",
              type: "topic",
              details: "2-cycles and parity of permutations.",
              children: [
                { id: "u3_tr1", label: "Transposition (2-cycle)", type: "subtopic" },
                { id: "u3_tr2", label: "Even and Odd Permutations", type: "subtopic" },
                { id: "u3_tr3", label: "Sign of Permutation sgn(σ)", type: "subtopic" }
              ]
            },
            {
              id: "u3_alt",
              label: "Alternating Group (Aₙ)",
              type: "topic",
              details: "Group of even permutations.",
              children: [
                { id: "u3_al1", label: "Definition & Order |Aₙ| = n!/2", type: "subtopic" },
                { id: "u3_al2", label: "Normal Subgroups of Sₙ", type: "subtopic" },
                { id: "u3_al3", label: "Simplicity of A₅", type: "subtopic" }
              ]
            }
          ]
        },
        {
          id: "unit4",
          label: "Unit 4: Group Actions & Intro to Rings",
          badge: "Unit 4",
          type: "unit",
          color: "#059669", // Emerald
          details: "Group actions, orbits, isotropy, class equation, groups of order p², and fundamental ring theory definitions.",
          children: [
            {
              id: "u4_action",
              label: "Group Actions",
              type: "topic",
              details: "Group elements acting on a set X.",
              children: [
                { id: "u4_a1", label: "Regular Action", type: "subtopic" },
                { id: "u4_a2", label: "Conjugation Action (g · x = gxg⁻¹)", type: "subtopic" },
                { id: "u4_a3", label: "Orbits & Orbit-Stabilizer Theorem", type: "subtopic" },
                { id: "u4_a4", label: "Isotropy / Stabilizer Subgroup", type: "subtopic" }
              ]
            },
            {
              id: "u4_class",
              label: "Class Equation & p-Groups",
              type: "topic",
              details: "Partitioning by conjugacy classes.",
              children: [
                { id: "u4_c1", label: "Conjugacy Classes", type: "subtopic" },
                { id: "u4_c2", label: "Class Equation for Finite Groups", type: "subtopic" },
                { id: "u4_c3", label: "Groups of Order p² (Abelian Properties)", type: "subtopic" }
              ]
            },
            {
              id: "u4_rings",
              label: "Ring Theory Foundations",
              type: "topic",
              details: "Algebraic structures with two binary operations (+, ·).",
              children: [
                { id: "u4_r1", label: "Ring Definitions & Axioms", type: "subtopic" },
                { id: "u4_r2", label: "Subrings & Examples (Gaussian Integers ℤ[i], Matrix Rings)", type: "subtopic" },
                { id: "u4_r3", label: "Quaternions (ℍ)", type: "subtopic" },
                { id: "u4_r4", label: "Ideals (Left, Right, Two-sided) & Quotient Rings R/I", type: "subtopic" },
                { id: "u4_r5", label: "Ring Homomorphisms", type: "subtopic" }
              ]
            }
          ]
        },
        {
          id: "unit5",
          label: "Unit 5: Integral Domains & Polynomial Rings",
          badge: "Unit 5",
          type: "unit",
          color: "#7C3AED", // Violet
          details: "Integral domains, division rings, fields, field of fractions, polynomial rings, division algorithm, and hypercomplex algebras.",
          children: [
            {
              id: "u5_domain",
              label: "Integral Domains & Fields",
              type: "topic",
              details: "Commutative rings with no zero divisors.",
              children: [
                { id: "u5_d1", label: "Integral Domain Definition", type: "subtopic" },
                { id: "u5_d2", label: "Division Rings / Skew Fields", type: "subtopic" },
                { id: "u5_d3", label: "Commutative Rings & Fields", type: "subtopic" },
                { id: "u5_d4", label: "Field of Fractions", type: "subtopic" }
              ]
            },
            {
              id: "u5_poly",
              label: "Polynomial Rings & Ideals",
              type: "topic",
              details: "Polynomials over fields and ideal structures.",
              children: [
                { id: "u5_p1", label: "Polynomial Ring R[x]", type: "subtopic" },
                { id: "u5_p2", label: "Division Algorithm in F[x]", type: "subtopic" },
                { id: "u5_p3", label: "Ideals of Polynomial Rings over a Field", type: "subtopic" }
              ]
            },
            {
              id: "u5_algebra",
              label: "Algebraic Systems",
              type: "topic",
              details: "Real, Complex, Quaternion, and Octonion algebras.",
              children: [
                { id: "u5_ag1", label: "Algebra of Reals ℝ & Complex Numbers ℂ", type: "subtopic" },
                { id: "u5_ag2", label: "Quaternions ℍ (Non-commutative)", type: "subtopic" },
                { id: "u5_ag3", label: "Octonions 𝕃 (Non-associative)", type: "subtopic" }
              ]
            }
          ]
        }
      ]
    }
  },
  "MATMJ52": {
    id: "MATMJ52",
    code: "MATMJ52",
    title: "Metric Spaces",
    department: "Department of Mathematics",
    semester: 5,
    credits: 3,
    course_type: "Major",
    summary: "Comprehensive structure covering Metric Space Topology, Subspaces, Heine-Borel Compactness, Connectedness, Completion of Rationals, Continuous & Isometric Mappings, Uniform Convergence, and Arzelà-Ascoli Theorem.",
    root: {
      id: "root",
      label: "Metric Spaces",
      badge: "MATMJ52 • Sem 5",
      type: "root",
      details: "3 Credits Major Course. Foundations of Topological and Analytical Metric Structures.",
      children: [
        {
          id: "unit1",
          label: "Unit 1: Topology of Metric Spaces",
          badge: "Unit 1",
          type: "unit",
          color: "#4F46E5",
          details: "Metric space axioms, standard examples, open and closed sets, neighborhoods, convergence, induced topology, and boundary operations.",
          children: [
            {
              id: "u1_def",
              label: "Metric Space Definitions & Examples",
              type: "topic",
              details: "Distance functions and standard spaces.",
              children: [
                { id: "u1_d1", label: "Metric Axioms: Non-negativity, Symmetry, Triangle Inequality d(x,z) ≤ d(x,y)+d(y,z)", type: "subtopic" },
                { id: "u1_d2", label: "Euclidean & Discrete Metrics (ℝ<sup>n</sup>, d<sub>disc</sub>)", type: "subtopic" },
                { id: "u1_d3", label: "Sequence & Function Spaces (ℓᵖ, C[a,b])", type: "subtopic" }
              ]
            },
            {
              id: "u1_sets",
              label: "Open & Closed Sets",
              type: "topic",
              details: "Ball neighborhoods and subset classifications.",
              children: [
                { id: "u1_s1", label: "Open Balls Bᵣ(x) & Open Sets", type: "subtopic" },
                { id: "u1_s2", label: "Closed Sets & Closed Balls B̄ᵣ(x)", type: "subtopic" },
                { id: "u1_s3", label: "Arbitrary Unions & Finite Intersections", type: "subtopic" }
              ]
            },
            {
              id: "u1_conv",
              label: "Neighborhoods, Convergence & Topology",
              type: "topic",
              details: "Limit points and convergent sequences.",
              children: [
                { id: "u1_c1", label: "Neighborhoods N<sub>r</sub>(x) & Limit Points x'", type: "subtopic" },
                { id: "u1_c2", label: "Convergent Sequences (d(xₙ, x) → 0)", type: "subtopic" },
                { id: "u1_c3", label: "Topology Induced by a Metric τ<sub>d</sub>", type: "subtopic" }
              ]
            },
            {
              id: "u1_ops",
              label: "Interior, Closure & Boundary",
              type: "topic",
              details: "Fundamental set-theoretic operations.",
              children: [
                { id: "u1_o1", label: "Interior Int(A) - Largest Open Set", type: "subtopic" },
                { id: "u1_o2", label: "Closure Ā = A ∪ A' - Smallest Closed Set", type: "subtopic" },
                { id: "u1_o3", label: "Boundary ∂A = Ā ∩ (X \\ A)̄", type: "subtopic" }
              ]
            }
          ]
        },
        {
          id: "unit2",
          label: "Unit 2: Subspaces, Compactness & Connectedness",
          badge: "Unit 2",
          type: "unit",
          color: "#0891B2",
          details: "Metric subspaces, completeness, Heine-Borel theorem, sequential compactness, and path-connected spaces.",
          children: [
            {
              id: "u2_sub",
              label: "Subspaces & Completeness",
              type: "topic",
              details: "Inherited metrics and Cauchy completeness.",
              children: [
                { id: "u2_sb1", label: "Subspace Metric d<sub>Y</sub> = d|<sub>Y×Y</sub>", type: "subtopic" },
                { id: "u2_sb2", label: "Cauchy Sequences & Complete Spaces", type: "subtopic" },
                { id: "u2_sb3", label: "Closed Subsets of Complete Spaces", type: "subtopic" }
              ]
            },
            {
              id: "u2_comp",
              label: "Compactness & Heine-Borel",
              type: "topic",
              details: "Coverings, sequential compactness, and boundedness.",
              children: [
                { id: "u2_cm1", label: "Open Coverings & Compact Sets", type: "subtopic" },
                { id: "u2_cm2", label: "Heine-Borel Theorem (Closed & Bounded in ℝⁿ)", type: "subtopic" },
                { id: "u2_cm3", label: "Sequential Compactness (Bolzano-Weierstrass)", type: "subtopic" }
              ]
            },
            {
              id: "u2_conn",
              label: "Connectedness & Path-Connectedness",
              type: "topic",
              details: "Topological separation and continuous paths.",
              children: [
                { id: "u2_cn1", label: "Connected vs Disconnected Sets", type: "subtopic" },
                { id: "u2_cn2", label: "Path-Connected Spaces & Curves", type: "subtopic" },
                { id: "u2_cn3", label: "Continuous Image of Connected Sets", type: "subtopic" }
              ]
            }
          ]
        },
        {
          id: "unit3",
          label: "Unit 3: Completion, Separability & Continuous Mappings",
          badge: "Unit 3",
          type: "unit",
          color: "#D97706",
          details: "Cantor's intersection theorem, construction of real numbers, dense subsets, separable metric spaces, continuous & isometric functions, and equivalent metrics.",
          children: [
            {
              id: "u3_cantor",
              label: "Cantor's Theorem & Completion of ℚ",
              type: "topic",
              details: "Nested sets and metric completion.",
              children: [
                { id: "u3_ct1", label: "Cantor's Intersection Theorem (∩ Fₙ ≠ ∅)", type: "subtopic" },
                { id: "u3_ct2", label: "Completion of Incomplete Metric Spaces", type: "subtopic" },
                { id: "u3_ct3", label: "Construction of ℝ as Completion of ℚ", type: "subtopic" }
              ]
            },
            {
              id: "u3_dense",
              label: "Dense Subsets & Separable Spaces",
              type: "topic",
              details: "Countable dense subsets and structural properties.",
              children: [
                { id: "u3_ds1", label: "Dense Subsets (Ā = X)", type: "subtopic" },
                { id: "u3_ds2", label: "Separable Metric Spaces (Countable Dense Set)", type: "subtopic" },
                { id: "u3_ds3", label: "Separability of ℝⁿ & ℓ² Spaces", type: "subtopic" }
              ]
            },
            {
              id: "u3_map",
              label: "Continuous Functions, Isometries & Homeomorphisms",
              type: "topic",
              details: "Mappings preserving metric and topological structures.",
              children: [
                { id: "u3_mp1", label: "Continuous Functions & (ε, δ)-Criterion", type: "subtopic" },
                { id: "u3_mp2", label: "Uniform Continuity & Compact Domains", type: "subtopic" },
                { id: "u3_mp3", label: "Isometry (Distance-Preserving Mapping d(f(x),f(y))=d(x,y))", type: "subtopic" },
                { id: "u3_mp4", label: "Homeomorphism & Equivalent Metrics", type: "subtopic" }
              ]
            }
          ]
        },
        {
          id: "unit4",
          label: "Unit 4: Sequences & Series of Functions",
          badge: "Unit 4",
          type: "unit",
          color: "#059669",
          details: "Pointwise and uniform convergence, Cauchy criterion, Weierstrass M-test, Abel's and Dirichlet's tests, and uniform limits of continuous functions.",
          children: [
            {
              id: "u4_conv",
              label: "Pointwise vs Uniform Convergence",
              type: "topic",
              details: "Types of function sequence convergence.",
              children: [
                { id: "u4_cv1", label: "Pointwise Convergence fₙ(x) → f(x)", type: "subtopic" },
                { id: "u4_cv2", label: "Uniform Convergence f<sub>n</sub> ⇉ f (Sup-norm ||f<sub>n</sub> - f||<sub>∞</sub> → 0)", type: "subtopic" },
                { id: "u4_cv3", label: "Cauchy Criterion for Uniform Convergence", type: "subtopic" }
              ]
            },
            {
              id: "u4_tests",
              label: "Tests for Uniform Convergence",
              type: "topic",
              details: "Analytical tests for series of functions.",
              children: [
                { id: "u4_ts1", label: "Weierstrass M-Test (|fₙ(x)| ≤ Mₙ)", type: "subtopic" },
                { id: "u4_ts2", label: "Abel's Test for Uniform Convergence", type: "subtopic" },
                { id: "u4_ts3", label: "Dirichlet's Test for Series of Functions", type: "subtopic" }
              ]
            },
            {
              id: "u4_cont",
              label: "Uniform Convergence & Continuity",
              type: "topic",
              details: "Interchange of limits and continuous bounds.",
              children: [
                { id: "u4_cn1", label: "Uniform Limit of Continuous Functions is Continuous", type: "subtopic" },
                { id: "u4_cn2", label: "Dini's Theorem for Monotone Sequences", type: "subtopic" }
              ]
            }
          ]
        },
        {
          id: "unit5",
          label: "Unit 5: Integration, Differentiation & Arzelà-Ascoli Theorem",
          badge: "Unit 5",
          type: "unit",
          color: "#7C3AED",
          details: "Uniform convergence with Riemann-Stieltjes integration, differentiation, Weierstrass approximation theorem, equicontinuity, and Arzelà-Ascoli theorem.",
          children: [
            {
              id: "u5_calculus",
              label: "Uniform Convergence with Calculus",
              type: "topic",
              details: "Interchanging limits with integrals and derivatives.",
              children: [
                { id: "u5_cl1", label: "Uniform Convergence & Riemann-Stieltjes Integration (∫ fₙ dg → ∫ f dg)", type: "subtopic" },
                { id: "u5_cl2", label: "Uniform Convergence & Differentiation (fₙ' → f')", type: "subtopic" }
              ]
            },
            {
              id: "u5_approx",
              label: "Weierstrass Approximation Theorem",
              type: "topic",
              details: "Polynomial approximation of continuous functions.",
              children: [
                { id: "u5_ap1", label: "Density of Polynomials in C[a,b]", type: "subtopic" },
                { id: "u5_ap2", label: "Bernstein Polynomials Construction", type: "subtopic" }
              ]
            },
            {
              id: "u5_ascoli",
              label: "Equicontinuity & Arzelà-Ascoli Theorem",
              type: "topic",
              details: "Compactness criteria in continuous function space C(K).",
              children: [
                { id: "u5_ac1", label: "Equicontinuous Family of Functions", type: "subtopic" },
                { id: "u5_ac2", label: "Uniformly Bounded Families", type: "subtopic" },
                { id: "u5_ac3", label: "Arzelà-Ascoli Theorem (Relative Compactness in C(K))", type: "subtopic" }
              ]
            }
          ]
        }
      ]
    }
  }
};

/**
 * Dynamically builds a structured Mind Map object from a standard course syllabus JSON object.
 */
function buildMindMapFromPaper(paper, deptName = "Department") {
  if (!paper) return null;
  const code = paper.code || "COURSE";
  
  if (PREDEFINED_MINDMAPS[code]) {
    return PREDEFINED_MINDMAPS[code];
  }

  const unitColors = ["#4F46E5", "#0891B2", "#D97706", "#059669", "#7C3AED", "#DB2777", "#2563EB"];

  const rootNode = {
    id: "root",
    label: paper.name || "Course Syllabus",
    badge: `${code} • Sem ${paper.semester || 'UG'}`,
    type: "root",
    details: `${paper.credits || 4} Credits ${paper.course_type || 'Core'} Course. Syllabus breakdown tree.`,
    children: []
  };

  if (paper.syllabus && Array.isArray(paper.syllabus)) {
    paper.syllabus.forEach((u, idx) => {
      const color = unitColors[idx % unitColors.length];
      const unitNode = {
        id: `unit_${u.unit}`,
        label: `Unit ${u.unit}`,
        badge: `Unit ${u.unit}`,
        type: "unit",
        color: color,
        details: u.topics || "",
        children: []
      };

      // Split topics by sentence or punctuation to create subtopic nodes
      if (u.topics) {
        const rawTopics = u.topics
          .replace(/\d+\s*(Texts|Course Title|Hours)?.*$/gi, '') // Clean tail numbers
          .split(/(?:\.|\;|\:)\s+/)
          .map(t => t.trim())
          .filter(t => t.length > 2);

        rawTopics.forEach((t, tIdx) => {
          unitNode.children.push({
            id: `u${u.unit}_t${tIdx+1}`,
            label: t,
            type: "topic",
            details: t
          });
        });
      }

      rootNode.children.push(unitNode);
    });
  }

  return {
    id: code,
    code: code,
    title: paper.name,
    department: deptName,
    credits: paper.credits,
    course_type: paper.course_type,
    root: rootNode
  };
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PREDEFINED_MINDMAPS, buildMindMapFromPaper };
}
