/**
 * SCIQB - Mind Map Data & Dynamic Generator
 * Grounded in BHU UG NEP Syllabus
 */

const PREDEFINED_MINDMAPS = {
  "MATMJ51": {
    id: "MATMJ51",
    code: "MATMJ51",
    title: "Abstract Algebra",
    department: "Department of Mathematics",
    semester: 5,
    credits: 4,
    course_type: "Major",
    summary: "Comprehensive structure covering Group Theory, Isomorphism Theorems, Permutation Groups, Group Actions, Ring Theory, and Polynomial Algebras.",
    root: {
      id: "root",
      label: "Abstract Algebra",
      badge: "MATMJ51 • Sem 5",
      type: "root",
      details: "4 Credits Major Course. Foundations of Algebraic Structures.",
      children: [
        {
          id: "unit1",
          label: "Unit 1: Group Theory & Cosets",
          badge: "Unit 1",
          type: "unit",
          color: "#4F46E5",
          details: "Homomorphisms, Isomorphisms, Subgroups, Cosets, and classical number theory applications of Lagrange's Theorem.",
          children: [
            {
              id: "u1_homo",
              label: "Homomorphism & Isomorphism",
              type: "topic",
              details: "Structure-preserving mappings between groups.",
              children: [
                { id: "u1_h1", label: "Homomorphism: $\\phi(ab) = \\phi(a)\\phi(b)$", type: "subtopic", details: "A mapping $\\phi: G \\to G'$ preserving group operations." },
                { id: "u1_h2", label: "Isomorphism (Bijective Homomorphism: $G \\cong G'$)", type: "subtopic", details: "Bijective structure-preserving mapping between groups." },
                { id: "u1_h3", label: "Kernel $\\ker\\phi = \\{g \\in G \\mid \\phi(g) = e'\\}$ & Image", type: "subtopic", details: "Properties of kernel and image under group homomorphisms." }
              ]
            },
            {
              id: "u1_sub",
              label: "Subgroups & Generators",
              type: "topic",
              details: "Subgroup criteria and generators of groups.",
              children: [
                { id: "u1_s1", label: "Subgroup Criteria: $H \\le G$ ($ab^{-1} \\in H$)", type: "subtopic", details: "One-step and two-step subgroup tests." },
                { id: "u1_s2", label: "Group Generated by Subset $\\langle S \\rangle$", type: "subtopic", details: "Smallest subgroup containing subset $S$." },
                { id: "u1_s3", label: "Center of a Group $Z(G) = \\{z \\in G \\mid zg = gz,\\, \\forall g \\in G\\}$", type: "subtopic", details: "Abelian characteristic subgroup of elements commuting with all group elements." }
              ]
            },
            {
              id: "u1_coset",
              label: "Cosets & Lagrange Applications",
              type: "topic",
              details: "Partitioning groups and applying order relations.",
              children: [
                { id: "u1_c1", label: "Left & Right Cosets ($aH$ / $Ha$)", type: "subtopic", details: "Equivalence classes partitioning the group $G$." },
                { id: "u1_c2", label: "Lagrange's Theorem: $|H| \\mid |G|$ ($[G:H] = |G|/|H|$)", type: "subtopic", details: "Order of any subgroup divides the order of a finite group." },
                { id: "u1_c3", label: "Euler's Totient Theorem: $a^{\\phi(n)} \\equiv 1 \\pmod n$", type: "subtopic", details: "Number theoretic consequence of Lagrange's theorem on $U(n)$." },
                { id: "u1_c4", label: "Fermat's Little Theorem: $a^p \\equiv a \\pmod p$", type: "subtopic", details: "Special case of Euler's theorem for prime moduli." },
                { id: "u1_c5", label: "Wilson's Theorem: $(p-1)! \\equiv -1 \\pmod p$", type: "subtopic", details: "Characterization of prime numbers." }
              ]
            }
          ]
        },
        {
          id: "unit2",
          label: "Unit 2: Isomorphism Theorems & Quotients",
          badge: "Unit 2",
          type: "unit",
          color: "#0891B2",
          details: "Products of groups, normal subgroups, factor groups, fundamental isomorphism theorems, and commutators.",
          children: [
            {
              id: "u2_prod",
              label: "Product of Groups",
              type: "topic",
              details: "Combining groups via direct products.",
              children: [
                { id: "u2_p1", label: "External Direct Product $G \\times H$", type: "subtopic", details: "Group of pairs $(g, h)$ with component-wise multiplication." },
                { id: "u2_p2", label: "Internal Direct Product $G = HK$", type: "subtopic", details: "Factorization into normal subgroups with $H \\cap K = \\{e\\}$." }
              ]
            },
            {
              id: "u2_normal",
              label: "Normal Subgroups & Quotient Groups",
              type: "topic",
              details: "Subgroups invariant under conjugation.",
              children: [
                { id: "u2_n1", label: "Normal Subgroup Criteria: $gNg^{-1} = N$ ($N \\trianglelefteq G$)", type: "subtopic", details: "Invariance under inner automorphisms." },
                { id: "u2_n2", label: "Quotient / Factor Group $G/N$", type: "subtopic", details: "Group of cosets under coset multiplication $(aN)(bN) = abN$." }
              ]
            },
            {
              id: "u2_theorems",
              label: "Isomorphism Theorems",
              type: "topic",
              details: "Core structural mapping theorems.",
              children: [
                { id: "u2_t1", label: "Fundamental Homomorphism Theorem: $G/\\ker\\phi \\cong \\operatorname{Im}\\phi$", type: "subtopic", details: "First Isomorphism Theorem relating quotient by kernel to the image." },
                { id: "u2_t2", label: "Second Isomorphism Theorem: $(HN)/N \\cong H/(H \\cap N)$", type: "subtopic", details: "Diamond isomorphism theorem for subgroups." },
                { id: "u2_t3", label: "Third Isomorphism Theorem: $(G/N)/(M/N) \\cong G/M$", type: "subtopic", details: "Quotient of quotients isomorphism theorem." }
              ]
            },
            {
              id: "u2_comm",
              label: "Commutator & Abelianization",
              type: "topic",
              details: "Measuring non-commutativity in groups.",
              children: [
                { id: "u2_cm1", label: "Commutator Element: $[g, h] = g^{-1}h^{-1}gh$", type: "subtopic", details: "Measure of failure of commutativity." },
                { id: "u2_cm2", label: "Derived Subgroup $G' = [G, G]$", type: "subtopic", details: "Subgroup generated by all commutator elements." },
                { id: "u2_cm3", label: "Abelianization: $G/G'$ is Abelian", type: "subtopic", details: "Largest abelian quotient of group $G$." }
              ]
            }
          ]
        },
        {
          id: "unit3",
          label: "Unit 3: Permutation & Symmetric Groups",
          badge: "Unit 3",
          type: "unit",
          color: "#D97706",
          details: "Symmetric groups $S_n$, cycle decompositions, transpositions, even/odd permutations, and alternating groups $A_n$.",
          children: [
            {
              id: "u3_sym",
              label: "Symmetric Group $S_n$",
              type: "topic",
              details: "Group of bijections on a set of $n$ elements.",
              children: [
                { id: "u3_sm1", label: "Permutation Notation: $\\sigma \\in S_n$ ($|S_n| = n!$)", type: "subtopic", details: "Two-line and cycle notations for permutations." },
                { id: "u3_sm2", label: "Disjoint Cycle Decomposition", type: "subtopic", details: "Every permutation is uniquely a product of disjoint cycles." },
                { id: "u3_sm3", label: "Cycle Order: $\\operatorname{ord}(\\sigma) = \\operatorname{lcm}(\\text{lengths})$", type: "subtopic", details: "Order of permutation equals least common multiple of its cycle lengths." }
              ]
            },
            {
              id: "u3_trans",
              label: "Transpositions & Parity",
              type: "topic",
              details: "2-cycles and parity of permutations.",
              children: [
                { id: "u3_tr1", label: "Transposition $(i\\, j)$ (2-cycle)", type: "subtopic", details: "Permutation swapping two elements." },
                { id: "u3_tr2", label: "Even and Odd Permutations", type: "subtopic", details: "Decomposition into even or odd number of transpositions." },
                { id: "u3_tr3", label: "Sign Homomorphism: $\\operatorname{sgn}(\\sigma) \\in \\{+1, -1\\}$", type: "subtopic", details: "Parity homomorphism $\\operatorname{sgn}: S_n \\to \\{\\pm 1\\}$." }
              ]
            },
            {
              id: "u3_alt",
              label: "Alternating Group $A_n$",
              type: "topic",
              details: "Group of even permutations.",
              children: [
                { id: "u3_al1", label: "Definition & Order: $|A_n| = \\frac{n!}{2}$", type: "subtopic", details: "Kernel of the sign homomorphism $\\operatorname{sgn}$." },
                { id: "u3_al2", label: "Normal Subgroup: $A_n \\trianglelefteq S_n$ ($[S_n:A_n] = 2$)", type: "subtopic", details: "Index 2 normal subgroup of the symmetric group." },
                { id: "u3_al3", label: "Simplicity of $A_n$ for $n \\ge 5$", type: "subtopic", details: "Non-existence of proper non-trivial normal subgroups." }
              ]
            }
          ]
        },
        {
          id: "unit4",
          label: "Unit 4: Group Actions & Intro to Rings",
          badge: "Unit 4",
          type: "unit",
          color: "#059669",
          details: "Group actions, orbits, isotropy, class equation, groups of order $p^2$, and fundamental ring theory definitions.",
          children: [
            {
              id: "u4_action",
              label: "Group Actions",
              type: "topic",
              details: "Group elements acting on a set $X$.",
              children: [
                { id: "u4_a1", label: "Group Action $G \\times X \\to X$", type: "subtopic", details: "Axioms: $e \\cdot x = x$ and $(gh) \\cdot x = g \\cdot (h \\cdot x)$." },
                { id: "u4_a2", label: "Conjugation Action: $g \\cdot x = gxg^{-1}$", type: "subtopic", details: "Action of group on itself by conjugation." },
                { id: "u4_a3", label: "Orbit-Stabilizer Theorem: $|G \\cdot x| = [G:G_x]$", type: "subtopic", details: "Size of orbit times size of stabilizer equals order of group." },
                { id: "u4_a4", label: "Stabilizer / Isotropy: $G_x = \\{g \\in G \\mid g \\cdot x = x\\}$", type: "subtopic", details: "Subgroup fixing the point $x$." }
              ]
            },
            {
              id: "u4_class",
              label: "Class Equation & $p$-Groups",
              type: "topic",
              details: "Partitioning by conjugacy classes.",
              children: [
                { id: "u4_c1", label: "Conjugacy Classes: $\\operatorname{Cl}(x) = \\{gxg^{-1} \\mid g \\in G\\}$", type: "subtopic", details: "Orbits under the conjugation action." },
                { id: "u4_c2", label: "Class Equation: $|G| = |Z(G)| + \\sum [G:C_G(x_i)]$", type: "subtopic", details: "Decomposition of finite group order into center and non-central conjugacy classes." },
                { id: "u4_c3", label: "Groups of Order $p^2$ are Abelian ($G \\cong \\mathbb{Z}_{p^2}$ or $\\mathbb{Z}_p \\times \\mathbb{Z}_p$)", type: "subtopic", details: "Structure theorem for groups of order $p^2$." }
              ]
            },
            {
              id: "u4_rings",
              label: "Ring Theory Foundations",
              type: "topic",
              details: "Algebraic structures with two binary operations $(+, \\cdot)$.",
              children: [
                { id: "u4_r1", label: "Ring Axioms $(R, +, \\cdot)$", type: "subtopic", details: "Abelian group under addition, associative multiplication, and distributive laws." },
                { id: "u4_r2", label: "Gaussian Integers $\\mathbb{Z}[i] = \\{a + bi \\mid a, b \\in \\mathbb{Z}\\}$ & Matrix Rings $M_n(R)$", type: "subtopic", details: "Standard examples of commutative and non-commutative rings." },
                { id: "u4_r3", label: "Hamilton's Quaternions $\\mathbb{H}$ ($i^2 = j^2 = k^2 = ijk = -1$)", type: "subtopic", details: "Non-commutative division algebra." },
                { id: "u4_r4", label: "Ideals & Quotient Ring $R/I$", type: "subtopic", details: "Subrings closed under absorption of external ring multiplication." },
                { id: "u4_r5", label: "Ring Homomorphisms: $\\phi(a+b)=\\phi(a)+\\phi(b)$, $\\phi(ab)=\\phi(a)\\phi(b)$", type: "subtopic", details: "Structure-preserving mappings between rings." }
              ]
            }
          ]
        },
        {
          id: "unit5",
          label: "Unit 5: Integral Domains & Polynomial Rings",
          badge: "Unit 5",
          type: "unit",
          color: "#7C3AED",
          details: "Integral domains, division rings, fields, field of fractions, polynomial rings, division algorithm, and hypercomplex algebras.",
          children: [
            {
              id: "u5_domain",
              label: "Integral Domains & Fields",
              type: "topic",
              details: "Commutative rings with no zero divisors.",
              children: [
                { id: "u5_d1", label: "Integral Domain ($ab = 0 \\implies a=0$ or $b=0$)", type: "subtopic", details: "Commutative ring with unity and no non-zero zero-divisors." },
                { id: "u5_d2", label: "Division Rings (Skew Fields)", type: "subtopic", details: "Ring where every non-zero element has a multiplicative inverse." },
                { id: "u5_d3", label: "Field $\\mathbb{F}$ (Commutative Division Ring)", type: "subtopic", details: "Algebraic structure supporting addition, subtraction, multiplication, and division." },
                { id: "u5_d4", label: "Field of Fractions $\\operatorname{Frac}(R)$", type: "subtopic", details: "Construction generalizing $\\mathbb{Q} = \\operatorname{Frac}(\\mathbb{Z})$." }
              ]
            },
            {
              id: "u5_poly",
              label: "Polynomial Rings & Ideals",
              type: "topic",
              details: "Polynomials over fields and ideal structures.",
              children: [
                { id: "u5_p1", label: "Polynomial Ring $R[x] = \\{\\sum a_i x^i \\mid a_i \\in R\\}$", type: "subtopic", details: "Ring of formal polynomials in indeterminate $x$." },
                { id: "u5_p2", label: "Division Algorithm in $F[x]$: $f(x) = q(x)g(x) + r(x)$", type: "subtopic", details: "Euclidean property of polynomial rings over fields." },
                { id: "u5_p3", label: "Principal Ideal Domain: $F[x]$ is a PID", type: "subtopic", details: "Every ideal in polynomial ring over field is generated by a single element." }
              ]
            },
            {
              id: "u5_algebra",
              label: "Hypercomplex Algebras",
              type: "topic",
              details: "Real, Complex, Quaternion, and Octonion algebras.",
              children: [
                { id: "u5_ag1", label: "Reals $\\mathbb{R}$ & Complex Numbers $\\mathbb{C}$", type: "subtopic", details: "1D and 2D normed division algebras." },
                { id: "u5_ag2", label: "Quaternions $\\mathbb{H}$ (4D Non-commutative Algebra)", type: "subtopic", details: "Frobenius theorem: division algebra over $\\mathbb{R}$." },
                { id: "u5_ag3", label: "Octonions $\\mathbb{O}$ (8D Non-associative Algebra)", type: "subtopic", details: "Alternative non-associative division algebra." }
              ]
            }
          ]
        }
      ]
    }
  },
  "MATMJ52": {
    id: "MATMJ52",
    code: "MATMJ52",
    title: "Metric Spaces",
    department: "Department of Mathematics",
    semester: 5,
    credits: 3,
    course_type: "Major",
    summary: "Comprehensive structure covering Metric Space Topology, Subspaces, Heine-Borel Compactness, Connectedness, Completion of Rationals, Continuous & Isometric Mappings, Uniform Convergence, and Arzelà-Ascoli Theorem.",
    root: {
      id: "root",
      label: "Metric Spaces",
      badge: "MATMJ52 • Sem 5",
      type: "root",
      details: "3 Credits Major Course. Foundations of Topological and Analytical Metric Structures.",
      children: [
        {
          id: "unit1",
          label: "Unit 1: Topology of Metric Spaces",
          badge: "Unit 1",
          type: "unit",
          color: "#4F46E5",
          details: "Metric space axioms, standard examples, open and closed sets, neighborhoods, convergence, induced topology, and boundary operations.",
          children: [
            {
              id: "u1_def",
              label: "Metric Space Definitions & Examples",
              type: "topic",
              details: "Distance functions and standard spaces.",
              children: [
                { id: "u1_d1", label: "Metric Axioms: $d(x,z) \\le d(x,y) + d(y,z)$", type: "subtopic", details: "Non-negativity ($d(x,y) \\ge 0$), identity of indiscernibles ($d(x,y)=0 \\iff x=y$), symmetry ($d(x,y)=d(y,x)$), and triangle inequality." },
                { id: "u1_d2", label: "Euclidean & Discrete Metrics ($\\mathbb{R}^n$, $d_{\\text{disc}}$)", type: "subtopic", details: "Euclidean distance on $\\mathbb{R}^n$ and discrete metric $d(x,y) = 1$ ($x \\ne y$)." },
                { id: "u1_d3", label: "Sequence & Function Spaces ($\\ell^p$, $C[a,b]$)", type: "subtopic", details: "Infinite sequence spaces $\\ell^p$ with $\\ell^p$-norm and continuous function spaces with supremum metric $d(f,g) = \\sup|f(x)-g(x)|$." }
              ]
            },
            {
              id: "u1_sets",
              label: "Open & Closed Sets",
              type: "topic",
              details: "Ball neighborhoods and subset classifications.",
              children: [
                { id: "u1_s1", label: "Open Ball: $B_r(x) = \\{y \\in X \\mid d(x,y) < r\\}$", type: "subtopic", details: "Open balls and definition of open sets as neighborhoods." },
                { id: "u1_s2", label: "Closed Ball: $\\overline{B}_r(x) = \\{y \\in X \\mid d(x,y) \\le r\\}$", type: "subtopic", details: "Closed sets as complements of open sets." },
                { id: "u1_s3", label: "Topology: Arbitrary $\\bigcup$ & Finite $\\bigcap$ of Open Sets", type: "subtopic", details: "Axioms of induced topology $\\tau_d$ on metric spaces." }
              ]
            },
            {
              id: "u1_conv",
              label: "Neighborhoods, Convergence & Limit Points",
              type: "topic",
              details: "Limit points and convergent sequences.",
              children: [
                { id: "u1_c1", label: "Neighborhoods $N_r(x)$ & Limit Points $x' \\in A'$", type: "subtopic", details: "Points whose deleted neighborhoods contain points of $A$." },
                { id: "u1_c2", label: "Convergent Sequences: $d(x_n, x) \\to 0$ as $n \\to \\infty$", type: "subtopic", details: "Uniqueness of metric limits and subsequence properties." },
                { id: "u1_c3", label: "Metric Topology $\\tau_d$ & Hausdorff Property", type: "subtopic", details: "Every metric space is a Hausdorff ($T_2$) topological space." }
              ]
            },
            {
              id: "u1_ops",
              label: "Interior, Closure & Boundary Operations",
              type: "topic",
              details: "Fundamental set-theoretic operations.",
              children: [
                { id: "u1_o1", label: "Interior $\\operatorname{Int}(A) = \\bigcup \\{U \\text{ open} \\mid U \\subseteq A\\}$", type: "subtopic", details: "Largest open subset contained in $A$." },
                { id: "u1_o2", label: "Closure $\\overline{A} = A \\cup A'$", type: "subtopic", details: "Smallest closed set containing subset $A$." },
                { id: "u1_o3", label: "Boundary: $\\partial A = \\overline{A} \\cap \\overline{X \\setminus A}$", type: "subtopic", details: "Frontier points of subset $A$." }
              ]
            }
          ]
        },
        {
          id: "unit2",
          label: "Unit 2: Subspaces, Compactness & Connectedness",
          badge: "Unit 2",
          type: "unit",
          color: "#0891B2",
          details: "Metric subspaces, completeness, Heine-Borel theorem, sequential compactness, and path-connected spaces.",
          children: [
            {
              id: "u2_sub",
              label: "Subspaces & Completeness",
              type: "topic",
              details: "Inherited metrics and Cauchy completeness.",
              children: [
                { id: "u2_sb1", label: "Subspace Metric: $d_Y = d|_{Y \\times Y}$", type: "subtopic", details: "Restriction of parent metric to subset $Y \\subseteq X$." },
                { id: "u2_sb2", label: "Cauchy Sequences: $d(x_n, x_m) < \\epsilon$ & Complete Spaces", type: "subtopic", details: "Space where every Cauchy sequence converges to a point in the space." },
                { id: "u2_sb3", label: "Closed Subsets of Complete Metric Spaces are Complete", type: "subtopic", details: "Preservation of completeness under closed subspace inclusion." }
              ]
            },
            {
              id: "u2_comp",
              label: "Compactness & Heine-Borel",
              type: "topic",
              details: "Coverings, sequential compactness, and boundedness.",
              children: [
                { id: "u2_cm1", label: "Compact Spaces (Every Open Cover Has a Finite Subcover)", type: "subtopic", details: "Heine-Borel property for general topological spaces." },
                { id: "u2_cm2", label: "Heine-Borel: $K \\subseteq \\mathbb{R}^n$ Compact $\\iff$ Closed & Bounded", type: "subtopic", details: "Characterization of compact sets in Euclidean spaces." },
                { id: "u2_cm3", label: "Sequential Compactness: Bolzano-Weierstrass Property", type: "subtopic", details: "Equivalence of compactness and sequential compactness in metric spaces." }
              ]
            },
            {
              id: "u2_conn",
              label: "Connectedness & Path-Connectedness",
              type: "topic",
              details: "Topological separation and continuous paths.",
              children: [
                { id: "u2_cn1", label: "Connected Spaces (Cannot Be Partitioned into Open Sets)", type: "subtopic", details: "Absence of non-trivial clopen subsets." },
                { id: "u2_cn2", label: "Path-Connected Spaces: Continuous Path $\\gamma: [0,1] \\to X$", type: "subtopic", details: "Points joinable by continuous curves; path-connectedness implies connectedness." },
                { id: "u2_cn3", label: "Continuous Image of Connected Sets is Connected", type: "subtopic", details: "Intermediate value theorem as a topological consequence." }
              ]
            }
          ]
        },
        {
          id: "unit3",
          label: "Unit 3: Completion, Separability & Continuous Mappings",
          badge: "Unit 3",
          type: "unit",
          color: "#D97706",
          details: "Cantor's intersection theorem, construction of real numbers, dense subsets, separable metric spaces, continuous & isometric functions, and equivalent metrics.",
          children: [
            {
              id: "u3_cantor",
              label: "Cantor's Theorem & Completion of $\\mathbb{Q}$",
              type: "topic",
              details: "Nested sets and metric completion.",
              children: [
                { id: "u3_ct1", label: "Cantor's Intersection Theorem: $\\bigcap_{n=1}^\\infty F_n \\ne \\emptyset$", type: "subtopic", details: "Non-empty intersection of nested non-empty closed sets with diameters tending to zero in complete spaces." },
                { id: "u3_ct2", label: "Completion of Incomplete Metric Spaces $(\\widetilde{X}, \\widetilde{d})$", type: "subtopic", details: "Equivalence classes of Cauchy sequences." },
                { id: "u3_ct3", label: "Construction of $\\mathbb{R}$ as Completion of $\\mathbb{Q}$", type: "subtopic", details: "Rigorous completion of rational numbers." }
              ]
            },
            {
              id: "u3_dense",
              label: "Dense Subsets & Separable Spaces",
              type: "topic",
              details: "Countable dense subsets and structural properties.",
              children: [
                { id: "u3_ds1", label: "Dense Subsets: $\\overline{A} = X$", type: "subtopic", details: "Every point in $X$ is within $\\epsilon$ of a point in $A$." },
                { id: "u3_ds2", label: "Separable Metric Space (Countable Dense Set $\\mathbb{Q} \\subset \\mathbb{R}$)", type: "subtopic", details: "Spaces with countable topological bases." },
                { id: "u3_ds3", label: "Separability of $\\mathbb{R}^n$ & $\\ell^2$ Spaces", type: "subtopic", details: "Standard examples of separable metric spaces." }
              ]
            },
            {
              id: "u3_map",
              label: "Continuous Functions, Isometries & Homeomorphisms",
              type: "topic",
              details: "Mappings preserving metric and topological structures.",
              children: [
                { id: "u3_mp1", label: "Continuity: $(\\epsilon, \\delta)$-Criterion & $f^{-1}(U)$ Open", type: "subtopic", details: "Topological characterization of continuous mappings." },
                { id: "u3_mp2", label: "Uniform Continuity on Compact Domains", type: "subtopic", details: "Heine-Cantor theorem: continuous functions on compact spaces are uniformly continuous." },
                { id: "u3_mp3", label: "Isometry: $d_Y(f(x), f(y)) = d_X(x, y)$", type: "subtopic", details: "Distance-preserving injective embedding." },
                { id: "u3_mp4", label: "Homeomorphism & Equivalent Metrics ($c_1 d_1 \\le d_2 \\le c_2 d_1$)", type: "subtopic", details: "Bijective continuous mappings with continuous inverses." }
              ]
            }
          ]
        },
        {
          id: "unit4",
          label: "Unit 4: Sequences & Series of Functions",
          badge: "Unit 4",
          type: "unit",
          color: "#059669",
          details: "Pointwise and uniform convergence, Cauchy criterion, Weierstrass M-test, Abel's and Dirichlet's tests, and uniform limits of continuous functions.",
          children: [
            {
              id: "u4_conv",
              label: "Pointwise vs Uniform Convergence",
              type: "topic",
              details: "Types of function sequence convergence.",
              children: [
                { id: "u4_cv1", label: "Pointwise Convergence: $f_n(x) \\to f(x),\\, \\forall x \\in E$", type: "subtopic", details: "Limit depends on both $\\epsilon$ and $x$." },
                { id: "u4_cv2", label: "Uniform Convergence: $f_n \\rightrightarrows f$ ($\\|f_n - f\\|_\\infty \\to 0$)", type: "subtopic", details: "Supremum norm metric convergence $\\lim_{n\\to\\infty} \\sup_{x\\in E} |f_n(x) - f(x)| = 0$." },
                { id: "u4_cv3", label: "Cauchy Criterion: $|f_n(x) - f_m(x)| < \\epsilon,\\, \\forall n, m \\ge N$", type: "subtopic", details: "Necessary and sufficient condition for uniform convergence." }
              ]
            },
            {
              id: "u4_tests",
              label: "Tests for Uniform Convergence",
              type: "topic",
              details: "Analytical tests for series of functions.",
              children: [
                { id: "u4_ts1", label: "Weierstrass $M$-Test: $|f_n(x)| \\le M_n$ with $\\sum M_n < \\infty$", type: "subtopic", details: "Dominated series test implying uniform and absolute convergence." },
                { id: "u4_ts2", label: "Abel's Test for Uniform Convergence $\\sum a_n(x) b_n(x)$", type: "subtopic", details: "Uniform convergence with bounded monotonic factors." },
                { id: "u4_ts3", label: "Dirichlet's Test for Function Series", type: "subtopic", details: "Bounded partial sums with uniformly vanishing monotonic coefficients." }
              ]
            },
            {
              id: "u4_cont",
              label: "Uniform Convergence & Continuity",
              type: "topic",
              details: "Interchange of limits and continuous bounds.",
              children: [
                { id: "u4_cn1", label: "Uniform Limit of Continuous Functions is Continuous", type: "subtopic", details: "$\\lim_{x\\to x_0} \\lim_{n\\to\\infty} f_n(x) = \\lim_{n\\to\\infty} \\lim_{x\\to x_0} f_n(x)$." },
                { id: "u4_cn2", label: "Dini's Theorem: Monotone Sequence on Compact Domain $\\implies f_n \\rightrightarrows f$", type: "subtopic", details: "Pointwise convergence to continuous limit implies uniform convergence." }
              ]
            }
          ]
        },
        {
          id: "unit5",
          label: "Unit 5: Integration, Differentiation & Arzelà-Ascoli Theorem",
          badge: "Unit 5",
          type: "unit",
          color: "#7C3AED",
          details: "Uniform convergence with Riemann-Stieltjes integration, differentiation, Weierstrass approximation theorem, equicontinuity, and Arzelà-Ascoli theorem.",
          children: [
            {
              id: "u5_calculus",
              label: "Uniform Convergence with Calculus",
              type: "topic",
              details: "Interchanging limits with integrals and derivatives.",
              children: [
                { id: "u5_cl1", label: "Integration: $\\lim_{n\\to\\infty} \\int f_n\\, dg = \\int (\\lim f_n)\\, dg$", type: "subtopic", details: "Interchange of uniform limits with Riemann-Stieltjes integration." },
                { id: "u5_cl2", label: "Differentiation: $\\left(\\lim f_n\\right)' = \\lim f_n'$ (When $f_n' \\rightrightarrows g$)", type: "subtopic", details: "Sufficient conditions for derivative interchange." }
              ]
            },
            {
              id: "u5_approx",
              label: "Weierstrass Approximation Theorem",
              type: "topic",
              details: "Polynomial approximation of continuous functions.",
              children: [
                { id: "u5_ap1", label: "Density: $\\overline{\\mathbb{R}[x]} = C[a, b]$ in Sup-Norm", type: "subtopic", details: "Every continuous real-valued function can be uniformly approximated by polynomials." },
                { id: "u5_ap2", label: "Bernstein Polynomials: $B_n(f)(x) = \\sum_{k=0}^n f(k/n) \\binom{n}{k} x^k (1-x)^{n-k}$", type: "subtopic", details: "Constructive proof of Weierstrass theorem on $[0,1]$." }
              ]
            },
            {
              id: "u5_ascoli",
              label: "Equicontinuity & Arzelà-Ascoli Theorem",
              type: "topic",
              details: "Compactness criteria in continuous function space $C(K)$.",
              children: [
                { id: "u5_ac1", label: "Equicontinuous Family: $|f(x) - f(y)| < \\epsilon,\\, \\forall f \\in \\mathcal{F}$", type: "subtopic", details: "Uniform modulus of continuity across an entire function family." },
                { id: "u5_ac2", label: "Uniformly Bounded Family: $\\|f\\|_\\infty \\le M,\\, \\forall f \\in \\mathcal{F}$", type: "subtopic", details: "Pointwise/uniform bounded family of functions." },
                { id: "u5_ac3", label: "Arzelà-Ascoli Theorem: $\\mathcal{F} \\subset C(K)$ Relatively Compact $\\iff$ Bounded & Equicontinuous", type: "subtopic", details: "Fundamental compactness characterization in function spaces." }
              ]
            }
          ]
        }
      ]
    }
  },
  "MATMJ53": {
    id: "MATMJ53",
    code: "MATMJ53",
    title: "Analytic Geometry",
    department: "Department of Mathematics",
    semester: 5,
    credits: 4,
    course_type: "Major",
    summary: "Systematic geometric foundations covering Polar Coordinates, 3D Vector Geometry of Planes & Lines, Spheres, Cones, Cylinders, Central Conicoids, and Quadric Surfaces.",
    root: {
      id: "root",
      label: "Analytic Geometry",
      badge: "MATMJ53 • Sem 5",
      type: "root",
      details: "4 Credits Major Course. Comprehensive 2D Polar & 3D Solid Geometry.",
      children: [
        {
          id: "unit1",
          label: "Unit 1: Polar Coordinates & Conics",
          badge: "Unit 1",
          type: "unit",
          color: "#4F46E5",
          details: "Distance between points, polar equations of straight lines, circles, and general conics with chords, tangents, normals, and chords of contact.",
          children: [
            {
              id: "u1_polar_coords",
              label: "Polar Coordinates & Metric",
              type: "topic",
              details: "Coordinate representation in $(r, \\theta)$ and fundamental distance metrics.",
              children: [
                { id: "u1_p1", label: "Coordinates: $(r, \\theta) \\leftrightarrow (x=r\\cos\\theta, y=r\\sin\\theta)$", type: "subtopic", details: "Transformation equations: $x = r\\cos\\theta$, $y = r\\sin\\theta$, $r^2 = x^2 + y^2$, $\\tan\\theta = y/x$." },
                { id: "u1_p2", label: "Distance: $d = \\sqrt{r_1^2 + r_2^2 - 2r_1r_2\\cos(\\theta_1 - \\theta_2)}$", type: "subtopic", details: "Distance between two points $P(r_1, \\theta_1)$ and $Q(r_2, \\theta_2)$ in polar coordinates." },
                { id: "u1_p3", label: "Triangle Area: $\\Delta = \\frac{1}{2}|r_1r_2\\sin(\\theta_2 - \\theta_1) + r_2r_3\\sin(\\theta_3 - \\theta_2) + r_3r_1\\sin(\\theta_1 - \\theta_3)|$", type: "subtopic", details: "Area of triangle formed by vertices $(r_1, \\theta_1)$, $(r_2, \\theta_2)$, and $(r_3, \\theta_3)$." }
              ]
            },
            {
              id: "u1_lines_circles",
              label: "Polar Equations of Lines & Circles",
              type: "topic",
              details: "Linear and circular loci in polar frame.",
              children: [
                { id: "u1_l1", label: "Straight Line (Normal Form): $\\frac{p}{r} = \\cos(\\theta - \\alpha)$", type: "subtopic", details: "$p$ is length of perpendicular from pole to line, and $\\alpha$ is its inclination with initial line." },
                { id: "u1_l2", label: "Line Through Two Points: $\\frac{\\sin(\\theta_2 - \\theta_1)}{r} + \\frac{\\sin(\\theta - \\theta_2)}{r_1} + \\frac{\\sin(\\theta_1 - \\theta)}{r_2} = 0$", type: "subtopic", details: "Determinant form of straight line passing through $(r_1, \\theta_1)$ and $(r_2, \\theta_2)$." },
                { id: "u1_c1", label: "Circle (Center $(r_0, \\theta_0)$, Radius $a$): $r^2 - 2rr_0\\cos(\\theta - \\theta_0) + r_0^2 = a^2$", type: "subtopic", details: "General polar equation of a circle with center $(r_0, \\theta_0)$ and radius $a$." },
                { id: "u1_c2", label: "Circle Through Pole: $r = 2a\\cos(\\theta - \\alpha)$", type: "subtopic", details: "Circle of diameter $2a$ passing through pole with diameter inclined at angle $\\alpha$." }
              ]
            },
            {
              id: "u1_polar_conics",
              label: "Polar Equations of Conics",
              type: "topic",
              details: "Focus at pole, semi-latus rectum $l$, and eccentricity $e$.",
              children: [
                { id: "u1_cn1", label: "Standard Conic: $\\frac{l}{r} = 1 + e\\cos\\theta$", type: "subtopic", details: "Focus at pole, initial line along axis: $e < 1$ (Ellipse), $e = 1$ (Parabola), $e > 1$ (Hyperbola)." },
                { id: "u1_cn2", label: "Chord Joining $\\alpha$ and $\\beta$: $\\frac{l}{r} = \\sec\\frac{\\beta-\\alpha}{2}\\cos\\left(\\theta - \\frac{\\alpha+\\beta}{2}\\right) + e\\cos\\theta$", type: "subtopic", details: "Equation of chord connecting two points with vectorial angles $\\alpha$ and $\\beta$ on the conic." },
                { id: "u1_cn3", label: "Tangent at Point $\\alpha$: $\\frac{l}{r} = \\cos(\\theta - \\alpha) + e\\cos\\theta$", type: "subtopic", details: "Limiting position of chord as $\\beta \\to \\alpha$." },
                { id: "u1_cn4", label: "Normal at Point $\\alpha$: $\\frac{l\\sin\\alpha}{r(1 + e\\cos\\alpha)} = \\sin(\\theta - \\alpha) + e\\sin\\theta$", type: "subtopic", details: "Straight line perpendicular to tangent at point of contact $(r_1, \\alpha)$." },
                { id: "u1_cn5", label: "Chord of Contact from $(r_1, \\theta_1)$: $(\\frac{l}{r} - e\\cos\\theta)(\\frac{l}{r_1} - e\\cos\\theta_1) = \\cos(\\theta - \\theta_1)$", type: "subtopic", details: "Polar line / chord of contact of tangents drawn from external point $(r_1, \\theta_1)$." }
              ]
            }
          ]
        },
        {
          id: "unit2",
          label: "Unit 2: Plane & Straight Line in $\\mathbb{R}^3$",
          badge: "Unit 2",
          type: "unit",
          color: "#0891B2",
          details: "Vector and Cartesian formulation of planes and straight lines, intersections, coplanarity, and shortest distance between skew lines.",
          children: [
            {
              id: "u2_planes",
              label: "Planes in $\\mathbb{R}^3$ (Vector & Cartesian)",
              type: "topic",
              details: "Linear equations in three variables and vector normals.",
              children: [
                { id: "u2_pl1", label: "Vector Normal Form: $\\vec{r}\\cdot\\hat{n} = d$ & $(\\vec{r} - \\vec{a})\\cdot\\vec{n} = 0$", type: "subtopic", details: "Vector plane equation with unit normal $\\hat{n}$ and perpendicular distance $d$." },
                { id: "u2_pl2", label: "Cartesian Linear Form: $Ax + By + Cz + D = 0$", type: "subtopic", details: "Normal direction ratios are $(A, B, C)$, distance from origin is $|D|/\\sqrt{A^2+B^2+C^2}$." },
                { id: "u2_pl3", label: "Plane Through Three Points: $[\vec{r} - \\vec{a},\\, \\vec{b} - \\vec{a},\\, \\vec{c} - \\vec{a}] = 0$", type: "subtopic", details: "Scalar triple product representation of plane through non-collinear points $\\vec{a}, \\vec{b}, \\vec{c}$." },
                { id: "u2_pl4", label: "Family of Intersecting Planes: $P_1 + \\lambda P_2 = 0$", type: "subtopic", details: "Linear pencil of planes passing through the line of intersection of $P_1 = 0$ and $P_2 = 0$." }
              ]
            },
            {
              id: "u2_lines",
              label: "Straight Line in Space",
              type: "topic",
              details: "Vector and symmetrical equations of 3D lines.",
              children: [
                { id: "u2_ln1", label: "Vector Form: $\\vec{r} = \\vec{a} + t\\vec{b}$", type: "subtopic", details: "Parametric equation of straight line through point $\\vec{a}$ parallel to direction vector $\\vec{b}$." },
                { id: "u2_ln2", label: "Symmetrical Form: $\\frac{x - x_1}{l} = \\frac{y - y_1}{m} = \\frac{z - z_1}{n}$", type: "subtopic", details: "Direction cosines $(l, m, n)$ with $l^2 + m^2 + n^2 = 1$." },
                { id: "u2_ln3", label: "Unsymmetric Form: $A_1x + B_1y + C_1z + D_1 = 0 = A_2x + B_2y + C_2z + D_2$", type: "subtopic", details: "Straight line represented as the intersection of two non-parallel planes." },
                { id: "u2_ln4", label: "Angle Between Line and Plane: $\\sin\\theta = \\frac{|aA + bB + cC|}{\\sqrt{a^2+b^2+c^2}\\sqrt{A^2+B^2+C^2}}$", type: "subtopic", details: "Angle between line with direction ratios $(a,b,c)$ and plane normal $(A,B,C)$." }
              ]
            },
            {
              id: "u2_skew_lines",
              label: "Coplanarity & Skew Lines",
              type: "topic",
              details: "Distance and intersection metrics between non-parallel lines.",
              children: [
                { id: "u2_sk1", label: "Coplanarity Condition: $(\\vec{a}_2 - \\vec{a}_1)\\cdot(\\vec{b}_1 \\times \\vec{b}_2) = 0$", type: "subtopic", details: "Determinant condition for lines $\\vec{r}=\\vec{a}_1+t\\vec{b}_1$ and $\\vec{r}=\\vec{a}_2+s\\vec{b}_2$ to lie in the same plane." },
                { id: "u2_sk2", label: "Shortest Distance (SD): $d = \\frac{|(\\vec{a}_2 - \\vec{a}_1)\\cdot(\\vec{b}_1 \\times \\vec{b}_2)|}{|\\vec{b}_1 \\times \\vec{b}_2|}$", type: "subtopic", details: "Perpendicular distance between two non-intersecting, non-parallel skew lines." },
                { id: "u2_sk3", label: "Line of Shortest Distance: $\\vec{r} = \\vec{p} + t(\\vec{b}_1 \\times \\vec{b}_2)$", type: "subtopic", details: "Equation of the unique line perpendicular to both given skew lines." }
              ]
            }
          ]
        },
        {
          id: "unit3",
          label: "Unit 3: The Sphere",
          badge: "Unit 3",
          type: "unit",
          color: "#D97706",
          details: "General equation, plane sections, 3D circles, tangent planes, radical planes, and orthogonal spheres.",
          children: [
            {
              id: "u3_sphere_eq",
              label: "Equation & Geometry of Sphere",
              type: "topic",
              details: "Quadratic locus of points equidistant from a center.",
              children: [
                { id: "u3_sp1", label: "General Equation: $x^2 + y^2 + z^2 + 2ux + 2vy + 2wz + d = 0$", type: "subtopic", details: "Center is $(-u, -v, -w)$ and radius is $R = \\sqrt{u^2 + v^2 + w^2 - d}$." },
                { id: "u3_sp2", label: "Diameter Form: $(x - x_1)(x - x_2) + (y - y_1)(y - y_2) + (z - z_1)(z - z_2) = 0$", type: "subtopic", details: "Sphere having $(x_1, y_1, z_1)$ and $(x_2, y_2, z_2)$ as endpoints of a diameter." },
                { id: "u3_sp3", label: "Sphere Through Four Non-Coplanar Points", type: "subtopic", details: "Unique sphere determined by determinant of four non-coplanar coordinates." }
              ]
            },
            {
              id: "u3_plane_section",
              label: "Plane Sections & 3D Circles",
              type: "topic",
              details: "Intersection of spheres and planes.",
              children: [
                { id: "u3_ps1", label: "Plane Section Circle: $S = 0,\\, P = 0$ (Radius $r_c = \\sqrt{R^2 - p^2}$)", type: "subtopic", details: "Plane section of a sphere is always a circle with center at the foot of perpendicular from sphere center to plane." },
                { id: "u3_ps2", label: "Great Circle: Plane through center ($p = 0$, $r_c = R$)", type: "subtopic", details: "Circle with maximum radius $R$ whose plane passes through the center of the sphere." },
                { id: "u3_ps3", label: "Spheres Through a Given Circle: $S + \\lambda P = 0$", type: "subtopic", details: "Family of spheres passing through the circular intersection of sphere $S=0$ and plane $P=0$." },
                { id: "u3_ps4", label: "Intersection of Two Spheres: $S_1 + \\lambda S_2 = 0$ (Radical Plane $S_1 - S_2 = 0$)", type: "subtopic", details: "Common circle with linear radical plane equation $S_1 - S_2 = 0$." }
              ]
            },
            {
              id: "u3_tangent_ortho",
              label: "Tangency & Orthogonal Spheres",
              type: "topic",
              details: "Tangent planes, condition of tangency, and orthogonality.",
              children: [
                { id: "u3_to1", label: "Tangent Plane at $(x_1, y_1, z_1)$: $xx_1 + yy_1 + zz_1 + u(x+x_1) + v(y+y_1) + w(z+z_1) + d = 0$", type: "subtopic", details: "Standard $T = 0$ representation of tangent plane to sphere." },
                { id: "u3_to2", label: "Tangency Condition: $d_{\\text{center}} = R$", type: "subtopic", details: "Plane touches sphere if and only if perpendicular distance from center equals radius $R$." },
                { id: "u3_to3", label: "Angle of Intersection: $\\cos\\theta = \\frac{r_1^2 + r_2^2 - d^2}{2r_1r_2}$", type: "subtopic", details: "Angle between two spheres with radii $r_1, r_2$ and center distance $d$." },
                { id: "u3_to4", label: "Orthogonality Condition: $2u_1u_2 + 2v_1v_2 + 2w_1w_2 = d_1 + d_2$", type: "subtopic", details: "Condition for two spheres to intersect orthogonally (at $\\theta = 90^\\circ$)." }
              ]
            }
          ]
        },
        {
          id: "unit4",
          label: "Unit 4: Cone and Cylinder",
          badge: "Unit 4",
          type: "unit",
          color: "#059669",
          details: "Cones with origin vertex, general quadratic cones, right circular cones, tangent planes, reciprocal cones, and cylinders.",
          children: [
            {
              id: "u4_cone_eq",
              label: "Cones & Vertex Conditions",
              type: "topic",
              details: "Surfaces generated by lines through a fixed vertex.",
              children: [
                { id: "u4_cn1", label: "Cone (Origin Vertex): $ax^2 + by^2 + cz^2 + 2fyz + 2gzx + 2hxy = 0$", type: "subtopic", details: "Every homogeneous equation of second degree in $x, y, z$ represents a cone with vertex at origin." },
                { id: "u4_cn2", label: "General 2nd Degree Cone Condition: $\\Delta = \\begin{vmatrix}a&h&g&u\\\\h&b&f&v\\\\g&f&c&w\\\\u&v&w&d\\end{vmatrix} = 0$", type: "subtopic", details: "Discriminant condition for general quadratic equation to represent a cone." },
                { id: "u4_cn3", label: "Intersection Lines with Plane: $\\frac{x}{l} = \\frac{y}{m} = \\frac{z}{n}$", type: "subtopic", details: "Two generating lines obtained by solving plane and cone equations simultaneously." }
              ]
            },
            {
              id: "u4_right_circular_cone",
              label: "Right Circular Cone & Tangent Planes",
              type: "topic",
              details: "Symmetric cones and enveloping surfaces.",
              children: [
                { id: "u4_rc1", label: "Right Circular Cone: $((\\vec{r}-\\vec{a})\\cdot\\hat{n})^2 = |\\vec{r}-\\vec{a}|^2 \\cos^2\\alpha$", type: "subtopic", details: "Vertex $\\vec{a}$, axis unit vector $\\hat{n}$, and semi-vertical angle $\\alpha$." },
                { id: "u4_rc2", label: "Tangent Plane: $x(ax_1+hy_1+gz_1) + y(hx_1+by_1+fz_1) + z(gx_1+fy_1+cz_1) = 0$", type: "subtopic", details: "Tangent plane along generator through point $(x_1, y_1, z_1)$." },
                { id: "u4_rc3", label: "Tangency Condition: $Al^2 + Bm^2 + Cn^2 + 2Fmn + 2Gnl + 2Hlm = 0$", type: "subtopic", details: "Condition for plane $lx + my + nz = 0$ to touch cone (capital letters are cofactors)." },
                { id: "u4_rc4", label: "Reciprocal Cone: $Ax^2 + By^2 + Cz^2 + 2Fyz + 2Gzx + 2Hxy = 0$", type: "subtopic", details: "Locus of normals drawn through vertex to tangent planes of original cone." }
              ]
            },
            {
              id: "u4_cylinder",
              label: "Cylinders & Enveloping Surfaces",
              type: "topic",
              details: "Surfaces generated by parallel generators.",
              children: [
                { id: "u4_cy1", label: "Cylinder with Parallel Generators $(l, m, n)$: $f\\left(x - \\frac{l}{n}z,\\, y - \\frac{m}{n}z\\right) = 0$", type: "subtopic", details: "Cylinder whose generators are parallel to line with direction ratios $(l, m, n)$." },
                { id: "u4_cy2", label: "Right Circular Cylinder: $\\text{dist}((x,y,z), \\text{Axis}) = r$", type: "subtopic", details: "Distance from point $(x,y,z)$ to axis line $\\frac{x-\\alpha}{l}=\\frac{y-\\beta}{m}=\\frac{z-\\gamma}{n}$ equals radius $r$." },
                { id: "u4_cy3", label: "Enveloping Cylinder to Sphere: $SS_1 = T^2$", type: "subtopic", details: "Tangent cylinder enveloping sphere with generators parallel to line $(l,m,n)$." }
              ]
            }
          ]
        },
        {
          id: "unit5",
          label: "Unit 5: Conicoids & Quadric Surfaces",
          badge: "Unit 5",
          type: "unit",
          color: "#7C3AED",
          details: "Central conicoids, paraboloids, tangent planes, six normals, plane sections, enveloping cones/cylinders, and quadric classification.",
          children: [
            {
              id: "u5_central_conicoids",
              label: "Central Conicoids & Paraboloids",
              type: "topic",
              details: "Standard quadratic surfaces in $\\mathbb{R}^3$.",
              children: [
                { id: "u5_cc1", label: "Ellipsoid: $\\frac{x^2}{a^2} + \\frac{y^2}{b^2} + \\frac{z^2}{c^2} = 1$", type: "subtopic", details: "Bounded closed quadric surface with three planes of symmetry." },
                { id: "u5_cc2", label: "Hyperboloid of One Sheet: $\\frac{x^2}{a^2} + \\frac{y^2}{b^2} - \\frac{z^2}{c^2} = 1$", type: "subtopic", details: "Doubly ruled quadric surface containing two families of generating straight lines." },
                { id: "u5_cc3", label: "Hyperboloid of Two Sheets: $\\frac{x^2}{a^2} - \\frac{y^2}{b^2} - \\frac{z^2}{c^2} = 1$", type: "subtopic", details: "Disconnected two-sheeted quadric surface." },
                { id: "u5_cc4", label: "Paraboloids: $\\frac{x^2}{a^2} \\pm \\frac{y^2}{b^2} = 2cz$", type: "subtopic", details: "Elliptic Paraboloid ($+$) and Hyperbolic Paraboloid ($-$, saddle surface)." }
              ]
            },
            {
              id: "u5_tangency_normals",
              label: "Tangent Planes & Six Normals",
              type: "topic",
              details: "Differential contact and normal lines to quadrics.",
              children: [
                { id: "u5_tn1", label: "Tangent Plane: $\\frac{xx_1}{a^2} + \\frac{yy_1}{b^2} + \\frac{zz_1}{c^2} = 1$ (Tangency: $a^2l^2 + b^2m^2 + c^2n^2 = p^2$)", type: "subtopic", details: "Plane $lx + my + nz = p$ touches central conicoid." },
                { id: "u5_tn2", label: "Normal Line: $\\frac{x - x_1}{x_1/a^2} = \\frac{y - y_1}{y_1/b^2} = \\frac{z - z_1}{z_1/c^2}$", type: "subtopic", details: "Perpendicular line to tangent plane at point of contact $(x_1, y_1, z_1)$." },
                { id: "u5_tn3", label: "Cone Through Six Normals from $(\\alpha, \\beta, \\gamma)$", type: "subtopic", details: "Exactly six normals can be drawn from any point $(\\alpha, \\beta, \\gamma)$ to a central conicoid, lying on a cone of 2nd degree." },
                { id: "u5_tn4", label: "Polar Plane: $\\frac{xx_0}{a^2} + \\frac{yy_0}{b^2} + \\frac{zz_0}{c^2} = 1$", type: "subtopic", details: "Harmonic conjugate polar plane of point $(x_0, y_0, z_0)$ with respect to conicoid." }
              ]
            },
            {
              id: "u5_plane_sections_quadrics",
              label: "Plane Sections & Quadric Classification",
              type: "topic",
              details: "Diametral planes, enveloping surfaces, and reduction of quadrics.",
              children: [
                { id: "u5_pq1", label: "Diametral Plane & Conjugate Diameters: $\\frac{xl}{a^2} + \\frac{ym}{b^2} + \\frac{zn}{c^2} = 0$", type: "subtopic", details: "Locus of midpoints of parallel chords with direction ratios $(l, m, n)$." },
                { id: "u5_pq2", label: "Enveloping Cone with Vertex $(x_1, y_1, z_1)$: $SS_1 = T^2$", type: "subtopic", details: "Tangent cone from external point $(x_1, y_1, z_1)$ enveloping a conicoid." },
                { id: "u5_pq3", label: "Enveloping Cylinder with Direction $(l, m, n)$: $SS_1 = T^2$", type: "subtopic", details: "Tangent cylinder with generators parallel to direction $(l, m, n)$." },
                { id: "u5_pq4", label: "Classification via Invariants $I_1, I_2, I_3, I_4$", type: "subtopic", details: "Orthogonal invariant reduction and classification of general second-degree equations in $\\mathbb{R}^3$." }
              ]
            }
          ]
        }
      ]
    }
  },
  "MATMV51": {
    id: "MATMV51",
    code: "MATMV51",
    title: "Optimization Techniques",
    department: "Department of Mathematics",
    semester: 5,
    credits: 4,
    course_type: "Minor (Vocational)",
    summary: "Systematic operations research and mathematical programming covering LPP Modeling, Simplex Methods, Duality, Transportation & Hungarian Assignment, Unconstrained Gradient Optimization, and KKT Constrained Non-Linear Programming.",
    root: {
      id: "root",
      label: "Optimization Techniques",
      badge: "MATMV51 • Sem 5",
      type: "root",
      details: "4 Credits Minor (Vocational) Course. Linear, Non-linear, and Applied Mathematical Optimization.",
      children: [
        {
          id: "unit1",
          label: "Unit 1: Linear Programming & Simplex Methods",
          badge: "Unit 1",
          type: "unit",
          color: "#4F46E5",
          details: "Mathematical modeling, convex sets, standard canonical forms, basic feasible solutions, the Simplex algorithm, Two-Phase method, and Big-M penalty method.",
          children: [
            {
              id: "u1_formulation",
              label: "LPP Formulation & Geometry",
              type: "topic",
              details: "Mathematical programming models and geometrical properties.",
              children: [
                { id: "u1_f1", label: "General LPP: $\\max\\, \\mathbf{c}^T\\mathbf{x} \\text{ s.t. } A\\mathbf{x} \\le \\mathbf{b},\\, \\mathbf{x} \\ge \\mathbf{0}$", type: "subtopic", details: "Decision variables, linear objective function, and structural resource constraints." },
                { id: "u1_f2", label: "Graphical Method (2-Variable Plane)", type: "subtopic", details: "Feasible region polygon and optimal solution at extreme corner points." },
                { id: "u1_f3", label: "Convex Sets & Extreme Points ($\\{x \\in \\mathbb{R}^n \\mid Ax \\le b\\}$)", type: "subtopic", details: "Convex combinations $\\lambda x_1 + (1-\\lambda)x_2$ and Fundamental Theorem of LPP." }
              ]
            },
            {
              id: "u1_canonical",
              label: "Standard Forms & Variables",
              type: "topic",
              details: "Algebraic preparation for matrix simplex tableau.",
              children: [
                { id: "u1_c1", label: "Canonical vs Standard Form ($A\\mathbf{x} = \\mathbf{b},\\, \\mathbf{b} \\ge \\mathbf{0}$)", type: "subtopic", details: "Conversion of inequalities into exact equality systems." },
                { id: "u1_c2", label: "Slack, Surplus & Artificial Variables ($s_i \\ge 0,\\, A_i \\ge 0$)", type: "subtopic", details: "Slack variables for $\\le$, surplus variables for $\\ge$, and artificial variables for identity basis." },
                { id: "u1_c3", label: "Basic Feasible Solutions (BFS: $\\mathbf{x}_B = B^{-1}\\mathbf{b} \\ge \\mathbf{0}$)", type: "subtopic", details: "Degenerate vs non-degenerate basic feasible solutions." }
              ]
            },
            {
              id: "u1_simplex",
              label: "The Simplex Algorithm & Big-M",
              type: "topic",
              details: "Iterative pivoting on polyhedral vertices.",
              children: [
                { id: "u1_sx1", label: "Simplex Method: Optimality Criterion ($z_j - c_j \\ge 0$)", type: "subtopic", details: "Incoming variable via most negative $z_j - c_j$ and outgoing variable via minimum ratio test $\\min\\{x_{Bi}/y_{ik} \\mid y_{ik} > 0\\}$." },
                { id: "u1_sx2", label: "Two-Phase Simplex Method", type: "subtopic", details: "Phase I minimizes sum of artificial variables $W = \\sum A_i$; Phase II optimizes original objective." },
                { id: "u1_sx3", label: "Big-$M$ Method: Objective $\\max\\, \\mathbf{c}^T\\mathbf{x} - M\\sum A_i$", type: "subtopic", details: "Charnes penalty method assigning large penalty $M > 0$ to artificial variables." }
              ]
            }
          ]
        },
        {
          id: "unit2",
          label: "Unit 2: Duality, Transportation & Assignment",
          badge: "Unit 2",
          type: "unit",
          color: "#0891B2",
          details: "Primal-dual relationships, dual simplex algorithm, transportation problems (NWCM, LCM, VAM, MODI), and Hungarian assignment method.",
          children: [
            {
              id: "u2_duality",
              label: "Duality in Linear Programming",
              type: "topic",
              details: "Mathematical duality and economic shadow prices.",
              children: [
                { id: "u2_d1", label: "Dual Formulation: $\\min\\, \\mathbf{b}^T\\mathbf{w} \\text{ s.t. } A^T\\mathbf{w} \\ge \\mathbf{c},\\, \\mathbf{w} \\ge \\mathbf{0}$", type: "subtopic", details: "Symmetric primal-dual pairs and duality matrix mapping." },
                { id: "u2_d2", label: "Weak & Strong Duality Theorems", type: "subtopic", details: "Weak Duality: $\\mathbf{c}^T\\mathbf{x} \\le \\mathbf{b}^T\\mathbf{w}$; Strong Duality: $\\max \\mathbf{c}^T\\mathbf{x}^* = \\min \\mathbf{b}^T\\mathbf{w}^*$." },
                { id: "u2_d3", label: "Complementary Slackness: $w_i(a_i^T x - b_i) = 0$", type: "subtopic", details: "Zero product optimality conditions between primal slack and dual variables." },
                { id: "u2_d4", label: "Dual Simplex Method (Starts Dual Feasible)", type: "subtopic", details: "Pivoting on infeasible primal basis maintaining dual optimality." }
              ]
            },
            {
              id: "u2_transportation",
              label: "Transportation Problem (TP)",
              type: "topic",
              details: "Network distribution optimization and optimality testing.",
              children: [
                { id: "u2_tp1", label: "TP Formulation: $\\min \\sum \\sum c_{ij}x_{ij}$ (Balanced $\\sum a_i = \\sum b_j$)", type: "subtopic", details: "Supply-demand network with $m+n-1$ basic variables." },
                { id: "u2_tp2", label: "Initial BFS: North-West Corner & Least Cost Methods", type: "subtopic", details: "Heuristic initial basis allocation methods." },
                { id: "u2_tp3", label: "Vogel's Approximation Method (VAM Penalty)", type: "subtopic", details: "Difference penalty method between two lowest cell costs per row/col." },
                { id: "u2_tp4", label: "MODI ($u$-$v$) Optimality Method: $\\Delta_{ij} = c_{ij} - (u_i + v_j)$", type: "subtopic", details: "Dual multipliers $u_i + v_j = c_{ij}$ for basic cells and evaluation $\\Delta_{ij} \\ge 0$." }
              ]
            },
            {
              id: "u2_assignment",
              label: "Assignment Problem",
              type: "topic",
              details: "Bipartite one-to-one matching optimization.",
              children: [
                { id: "u2_as1", label: "Mathematical Formulation: $\\min \\sum \\sum c_{ij} x_{ij},\\, x_{ij} \\in \\{0, 1\\}$", type: "subtopic", details: "Total unimodularity and square cost matrix $n \\times n$." },
                { id: "u2_as2", label: "Hungarian Algorithm (König's Theorem)", type: "subtopic", details: "Row and column reduction, covering zeros with minimum lines, and optimal assignment." }
              ]
            }
          ]
        },
        {
          id: "unit3",
          label: "Unit 3: Unconstrained Non-Linear Optimization",
          badge: "Unit 3",
          type: "unit",
          color: "#D97706",
          details: "Local and global extrema, first & second order optimality conditions, steepest descent gradient method, and conjugate gradient methods.",
          children: [
            {
              id: "u3_optimality_conditions",
              label: "Unconstrained Optimality Criteria",
              type: "topic",
              details: "Differential calculus criteria for unconstrained minima in $\\mathbb{R}^n$.",
              children: [
                { id: "u3_oc1", label: "Local & Global Minimizers: $f(\\mathbf{x}^*) \\le f(\\mathbf{x})$", type: "subtopic", details: "Strict vs non-strict local and global minima." },
                { id: "u3_oc2", label: "First-Order Necessary Condition (FONC): $\\nabla f(\\mathbf{x}^*) = \\mathbf{0}$", type: "subtopic", details: "Stationary point where all partial derivatives vanish." },
                { id: "u3_oc3", label: "Second-Order Necessary Condition (SONC): $\\nabla^2 f(\\mathbf{x}^*) \\succeq 0$", type: "subtopic", details: "Hessian matrix is positive semi-definite at a local minimizer." },
                { id: "u3_oc4", label: "Second-Order Sufficient Condition (SOSC): $\\nabla^2 f(\\mathbf{x}^*) \\succ 0$", type: "subtopic", details: "Strict local minimum guaranteed by positive definite Hessian matrix." }
              ]
            },
            {
              id: "u3_gradient_methods",
              label: "Gradient & Descent Methods",
              type: "topic",
              details: "Iterative search algorithms in multidimensional space.",
              children: [
                { id: "u3_gm1", label: "Steepest Descent: $\\mathbf{x}_{k+1} = \\mathbf{x}_k - \\alpha_k \\nabla f(\\mathbf{x}_k)$", type: "subtopic", details: "Moving in the negative gradient direction with line search step size $\\alpha_k$." },
                { id: "u3_gm2", label: "Exact Line Search: $\\min_{\\alpha > 0} f(\\mathbf{x}_k + \\alpha \\mathbf{d}_k)$", type: "subtopic", details: "One-dimensional step size optimization along search direction." },
                { id: "u3_gm3", label: "Conjugate Gradient Method: $\\mathbf{d}_i^T Q \\mathbf{d}_j = 0$ ($i \\ne j$)", type: "subtopic", details: "$Q$-orthogonal search directions with quadratic convergence in $n$ steps." },
                { id: "u3_gm4", label: "Fletcher-Reeves & Polak-Ribière Formulas", type: "subtopic", details: "Direction update parameter $\\beta_k$ for non-linear conjugate gradient descent." }
              ]
            }
          ]
        },
        {
          id: "unit4",
          label: "Unit 4: Constrained Optimization & KKT Conditions",
          badge: "Unit 4",
          type: "unit",
          color: "#059669",
          details: "Feasible and descent directions, Lagrangian functions, Fritz-John conditions, constraint qualifications, Karush-Kuhn-Tucker (KKT) conditions, and convex programming.",
          children: [
            {
              id: "u4_directions_lagrangian",
              label: "Feasible Directions & Lagrangian",
              type: "topic",
              details: "Geometry of constrained spaces and multiplier functions.",
              children: [
                { id: "u4_dl1", label: "Constrained Problem: $\\min f(\\mathbf{x}) \\text{ s.t. } g_i(\\mathbf{x}) \\le 0,\\, h_j(\\mathbf{x}) = 0$", type: "subtopic", details: "Standard non-linear programming problem with equality and inequality constraints." },
                { id: "u4_dl2", label: "Feasible & Descent Directions: $\\mathbf{d}^T \\nabla f(\\mathbf{x}^*) < 0$", type: "subtopic", details: "Directions maintaining constraint feasibility while decreasing objective." },
                { id: "u4_dl3", label: "Lagrangian: $\\mathcal{L}(\\mathbf{x}, \\boldsymbol{\\lambda}, \\boldsymbol{\\mu}) = f(\\mathbf{x}) + \\sum \\lambda_i g_i(\\mathbf{x}) + \\sum \\mu_j h_j(\\mathbf{x})$", type: "subtopic", details: "Combined objective with Lagrange multipliers $\\lambda_i \\ge 0$ and $\\mu_j \\in \\mathbb{R}$." }
              ]
            },
            {
              id: "u4_kkt_conditions",
              label: "KKT Optimality & Constraint Qualifications",
              type: "topic",
              details: "Fundamental necessary conditions for constrained non-linear programs.",
              children: [
                { id: "u4_kt1", label: "KKT Stationarity: $\\nabla f(\\mathbf{x}^*) + \\sum \\lambda_i^* \\nabla g_i(\\mathbf{x}^*) + \\sum \\mu_j^* \\nabla h_j(\\mathbf{x}^*) = \\mathbf{0}$", type: "subtopic", details: "First-order equilibrium between objective gradient and active constraint gradients." },
                { id: "u4_kt2", label: "KKT Complementary Slackness: $\\lambda_i^* g_i(\\mathbf{x}^*) = 0$ with $\\lambda_i^* \\ge 0$", type: "subtopic", details: "Inactive constraints ($g_i < 0$) have zero multipliers $\\lambda_i = 0$." },
                { id: "u4_kt3", label: "Constraint Qualifications (LICQ & Slater's Condition)", type: "subtopic", details: "Linear independence of active constraint gradients ensuring existence of KKT multipliers." },
                { id: "u4_kt4", label: "Fritz-John Optimality Conditions (Without Constraint Qualification)", type: "subtopic", details: "Generalization with multiplier $\\lambda_0 \\ge 0$ for the objective gradient." }
              ]
            },
            {
              id: "u4_convex_programming",
              label: "Convex Programming & Sufficiency",
              type: "topic",
              details: "Global optimality guarantees for convex functions.",
              children: [
                { id: "u4_cp1", label: "Convex Functions: $f(\\lambda \\mathbf{x} + (1-\\lambda)\\mathbf{y}) \\le \\lambda f(\\mathbf{x}) + (1-\\lambda)f(\\mathbf{y})$", type: "subtopic", details: "Epigraph convexity and second-derivative test $\\nabla^2 f(\\mathbf{x}) \\succeq 0$." },
                { id: "u4_cp2", label: "Sufficient Conditions: KKT is Necessary & Sufficient for Convex Programs", type: "subtopic", details: "Every local minimum of a convex program is a global minimum." },
                { id: "u4_cp3", label: "Engineering & Economic Applications", type: "subtopic", details: "Portfolio optimization, resource allocation, and machine learning loss minimization." }
              ]
            }
          ]
        }
      ]
    }
  }
};

/**
 * Dynamically builds a structured Mind Map object from a standard course syllabus JSON object.
 */
function buildMindMapFromPaper(paper, deptName = "Department") {
  if (!paper) return null;
  const code = paper.code || "COURSE";
  
  if (PREDEFINED_MINDMAPS[code]) {
    return PREDEFINED_MINDMAPS[code];
  }

  const unitColors = ["#4F46E5", "#0891B2", "#D97706", "#059669", "#7C3AED", "#DB2777", "#2563EB"];

  const rootNode = {
    id: "root",
    label: paper.name || "Course Syllabus",
    badge: `${code} • Sem ${paper.semester || 'UG'}`,
    type: "root",
    details: `${paper.credits || 4} Credits ${paper.course_type || 'Core'} Course. Syllabus breakdown tree.`,
    children: []
  };

  if (paper.syllabus && Array.isArray(paper.syllabus)) {
    paper.syllabus.forEach((u, idx) => {
      const color = unitColors[idx % unitColors.length];
      const unitNode = {
        id: `unit_${u.unit}`,
        label: `Unit ${u.unit}`,
        badge: `Unit ${u.unit}`,
        type: "unit",
        color: color,
        details: u.topics || "",
        children: []
      };

      // Split topics by sentence or punctuation to create subtopic nodes
      if (u.topics) {
        const rawTopics = u.topics
          .replace(/\d+\s*(Texts|Course Title|Hours)?.*$/gi, '') // Clean tail numbers
          .split(/(?:\.|\;|\:)\s+/)
          .map(t => t.trim())
          .filter(t => t.length > 2);

        rawTopics.forEach((t, tIdx) => {
          unitNode.children.push({
            id: `u${u.unit}_t${tIdx+1}`,
            label: t,
            type: "topic",
            details: t
          });
        });
      }

      rootNode.children.push(unitNode);
    });
  }

  return {
    id: code,
    code: code,
    title: paper.name,
    department: deptName,
    credits: paper.credits,
    course_type: paper.course_type,
    root: rootNode
  };
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PREDEFINED_MINDMAPS, buildMindMapFromPaper };
}
