// Automatically generated NEP Curriculum LaTeX PYQ data
export const NEP_LATEX_PYQ_DATA = [
  {
    "code": "CHB-101",
    "subject": "Structure and Bonding",
    "semester": 1,
    "year": "2016-17",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-101_StructureandBonding_SemI_2016-17.tex",
    "fileName": "CHB-101_StructureandBonding_SemI_2016-17.tex",
    "nepCode": "CHEMJ11 / CHEMN11",
    "oldCode": "CHB-101"
  },
  {
    "code": "CHB-101",
    "subject": "Structure and Bonding",
    "semester": 1,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-101_StructureandBonding_SemI_2022-23.tex",
    "fileName": "CHB-101_StructureandBonding_SemI_2022-23.tex",
    "nepCode": "CHEMJ11 / CHEMN11",
    "oldCode": "CHB-101"
  },
  {
    "code": "CHB-101",
    "subject": "Structure and Bonding",
    "semester": 1,
    "year": "2023-24",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-101_StructureandBonding_SemI_2023-24.tex",
    "fileName": "CHB-101_StructureandBonding_SemI_2023-24.tex",
    "nepCode": "CHEMJ11 / CHEMN11",
    "oldCode": "CHB-101"
  },
  {
    "code": "CHB-02A",
    "subject": "Ancillary Chemistry I",
    "semester": 2,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-02A_AncillaryChemistryI_SemII_2013-14.tex",
    "fileName": "CHB-02A_AncillaryChemistryI_SemII_2013-14.tex",
    "nepCode": "CHEMD11",
    "oldCode": "CHB-02A"
  },
  {
    "code": "CHB-02A",
    "subject": "Ancillary Chemistry I",
    "semester": 2,
    "year": "2023-24",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-02A_AncillaryChemistryI_SemII_2023-24.tex",
    "fileName": "CHB-02A_AncillaryChemistryI_SemII_2023-24.tex",
    "nepCode": "CHEMD11",
    "oldCode": "CHB-02A"
  },
  {
    "code": "CHB-201",
    "subject": "Inorganic and Physical Chemistry I",
    "semester": 2,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-201_InorganicandPhysicalChemistryI_SemII_2013-14.tex",
    "fileName": "CHB-201_InorganicandPhysicalChemistryI_SemII_2013-14.tex",
    "nepCode": "CHEMJ21 / CHEMN21",
    "oldCode": "CHB-201"
  },
  {
    "code": "CHB-201",
    "subject": "Inorganic and Physical Chemistry I",
    "semester": 2,
    "year": "2023-24",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-201_InorganicandPhysicalChemistryI_SemII_2023-24.tex",
    "fileName": "CHB-201_InorganicandPhysicalChemistryI_SemII_2023-24.tex",
    "nepCode": "CHEMJ21 / CHEMN21",
    "oldCode": "CHB-201"
  },
  {
    "code": "CHB-201",
    "subject": "Inorganic and Physical Chemistry I Old",
    "semester": 2,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-201_InorganicandPhysicalChemistryIOld_SemII_2013-14.tex",
    "fileName": "CHB-201_InorganicandPhysicalChemistryIOld_SemII_2013-14.tex",
    "nepCode": "CHEMJ21 / CHEMN21",
    "oldCode": "CHB-201"
  },
  {
    "code": "CHB-361",
    "subject": "Organic and Physical Chemistry",
    "semester": 3,
    "year": "2016-17",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-361_OrganicandPhysicalChemistry_SemIII_2016-17.tex",
    "fileName": "CHB-361_OrganicandPhysicalChemistry_SemIII_2016-17.tex",
    "nepCode": "CHEMJ32 / CHEMJ33",
    "oldCode": "CHB-301 / CHB-361"
  },
  {
    "code": "CHB-301",
    "subject": "Organic and Physical Chemistry II",
    "semester": 3,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-301_OrganicandPhysicalChemistryII_SemIII_2022-23.tex",
    "fileName": "CHB-301_OrganicandPhysicalChemistryII_SemIII_2022-23.tex",
    "nepCode": "CHEMJ32 / CHEMJ33",
    "oldCode": "CHB-301 / CHB-361"
  },
  {
    "code": "CHB-301",
    "subject": "Organic and Physical Chemistry II",
    "semester": 3,
    "year": "2023-24",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-301_OrganicandPhysicalChemistryII_SemIII_2023-24.tex",
    "fileName": "CHB-301_OrganicandPhysicalChemistryII_SemIII_2023-24.tex",
    "nepCode": "CHEMJ32 / CHEMJ33",
    "oldCode": "CHB-301 / CHB-361"
  },
  {
    "code": "CHB-04A",
    "subject": "Ancillary Chemistry II",
    "semester": 4,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-04A_AncillaryChemistryII_SemIV_2013-14.tex",
    "fileName": "CHB-04A_AncillaryChemistryII_SemIV_2013-14.tex",
    "nepCode": "CHEMD21",
    "oldCode": "CHB-04A"
  },
  {
    "code": "CHB-04A",
    "subject": "Ancillary Chemistry II",
    "semester": 4,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-04A_AncillaryChemistryII_SemIV_2022-23.tex",
    "fileName": "CHB-04A_AncillaryChemistryII_SemIV_2022-23.tex",
    "nepCode": "CHEMD21",
    "oldCode": "CHB-04A"
  },
  {
    "code": "CHB-04A",
    "subject": "Ancillary Chemistry II",
    "semester": 4,
    "year": "2023-24",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-04A_AncillaryChemistryII_SemIV_2023-24.tex",
    "fileName": "CHB-04A_AncillaryChemistryII_SemIV_2023-24.tex",
    "nepCode": "CHEMD21",
    "oldCode": "CHB-04A"
  },
  {
    "code": "CHB-401",
    "subject": "Inorganic Chemistry II and Selected Topics Old",
    "semester": 4,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-401_InorganicChemistryIIandSelectedTopicsOld_SemIV_2013-14.tex",
    "fileName": "CHB-401_InorganicChemistryIIandSelectedTopicsOld_SemIV_2013-14.tex",
    "nepCode": "CHEMJ41 / CHEMJ42",
    "oldCode": "CHB-401"
  },
  {
    "code": "CHB-401",
    "subject": "Inorganic and Organic Chemistry II",
    "semester": 4,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-401_InorganicandOrganicChemistryII_SemIV_2013-14.tex",
    "fileName": "CHB-401_InorganicandOrganicChemistryII_SemIV_2013-14.tex",
    "nepCode": "CHEMJ41 / CHEMJ42",
    "oldCode": "CHB-401"
  },
  {
    "code": "CHB-401",
    "subject": "Inorganic and Organic Chemistry II",
    "semester": 4,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-401_InorganicandOrganicChemistryII_SemIV_2022-23.tex",
    "fileName": "CHB-401_InorganicandOrganicChemistryII_SemIV_2022-23.tex",
    "nepCode": "CHEMJ41 / CHEMJ42",
    "oldCode": "CHB-401"
  },
  {
    "code": "CHB-401",
    "subject": "Inorganic and Organic Chemistry II",
    "semester": 4,
    "year": "2023-24",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-401_InorganicandOrganicChemistryII_SemIV_2023-24.tex",
    "fileName": "CHB-401_InorganicandOrganicChemistryII_SemIV_2023-24.tex",
    "nepCode": "CHEMJ41 / CHEMJ42",
    "oldCode": "CHB-401"
  },
  {
    "code": "CHB-501",
    "subject": "Analytical Chemistry I",
    "semester": 5,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-501_AnalyticalChemistryI_SemV_2013-14.tex",
    "fileName": "CHB-501_AnalyticalChemistryI_SemV_2013-14.tex",
    "nepCode": "CHEMJ51",
    "oldCode": "CHB-501"
  },
  {
    "code": "CHB-501",
    "subject": "Analytical Chemistry I",
    "semester": 5,
    "year": "2016-17",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-501_AnalyticalChemistryI_SemV_2016-17.tex",
    "fileName": "CHB-501_AnalyticalChemistryI_SemV_2016-17.tex",
    "nepCode": "CHEMJ51",
    "oldCode": "CHB-501"
  },
  {
    "code": "CHB-501",
    "subject": "Analytical Chemistry I",
    "semester": 5,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-501_AnalyticalChemistryI_SemV_2022-23.tex",
    "fileName": "CHB-501_AnalyticalChemistryI_SemV_2022-23.tex",
    "nepCode": "CHEMJ51",
    "oldCode": "CHB-501"
  },
  {
    "code": "CHB-505",
    "subject": "Environmental Chemistry and Nuclear Chemistry",
    "semester": 5,
    "year": "2016-17",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-505_EnvironmentalChemistryandNuclearChemistry_SemV_2016-17.tex",
    "fileName": "CHB-505_EnvironmentalChemistryandNuclearChemistry_SemV_2016-17.tex",
    "nepCode": "CHEMD31",
    "oldCode": "CHB-505"
  },
  {
    "code": "CHB-505",
    "subject": "Environmental and Nuclear Chemistry",
    "semester": 5,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-505_EnvironmentalandNuclearChemistry_SemV_2022-23.tex",
    "fileName": "CHB-505_EnvironmentalandNuclearChemistry_SemV_2022-23.tex",
    "nepCode": "CHEMD31",
    "oldCode": "CHB-505"
  },
  {
    "code": "CHB-502",
    "subject": "Inorganic Chemistry III",
    "semester": 5,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-502_InorganicChemistryIII_SemV_2013-14.tex",
    "fileName": "CHB-502_InorganicChemistryIII_SemV_2013-14.tex",
    "nepCode": "CHEMJ52",
    "oldCode": "CHB-502"
  },
  {
    "code": "CHB-502",
    "subject": "Inorganic Chemistry III",
    "semester": 5,
    "year": "2016-17",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-502_InorganicChemistryIII_SemV_2016-17.tex",
    "fileName": "CHB-502_InorganicChemistryIII_SemV_2016-17.tex",
    "nepCode": "CHEMJ52",
    "oldCode": "CHB-502"
  },
  {
    "code": "CHB-502",
    "subject": "Inorganic Chemistry III",
    "semester": 5,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-502_InorganicChemistryIII_SemV_2022-23.tex",
    "fileName": "CHB-502_InorganicChemistryIII_SemV_2022-23.tex",
    "nepCode": "CHEMJ52",
    "oldCode": "CHB-502"
  },
  {
    "code": "CHB-503",
    "subject": "Organic Chemistry III",
    "semester": 5,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-503_OrganicChemistryIII_SemV_2013-14.tex",
    "fileName": "CHB-503_OrganicChemistryIII_SemV_2013-14.tex",
    "nepCode": "CHEMJ53",
    "oldCode": "CHB-503"
  },
  {
    "code": "CHB-503",
    "subject": "Organic Chemistry III",
    "semester": 5,
    "year": "2016-17",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-503_OrganicChemistryIII_SemV_2016-17.tex",
    "fileName": "CHB-503_OrganicChemistryIII_SemV_2016-17.tex",
    "nepCode": "CHEMJ53",
    "oldCode": "CHB-503"
  },
  {
    "code": "CHB-503",
    "subject": "Organic Chemistry IV",
    "semester": 5,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-503_OrganicChemistryIV_SemV_2022-23.tex",
    "fileName": "CHB-503_OrganicChemistryIV_SemV_2022-23.tex",
    "nepCode": "CHEMJ53",
    "oldCode": "CHB-503"
  },
  {
    "code": "CHB-504",
    "subject": "Physical Chemistry III",
    "semester": 5,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-504_PhysicalChemistryIII_SemV_2013-14.tex",
    "fileName": "CHB-504_PhysicalChemistryIII_SemV_2013-14.tex",
    "nepCode": "CHEMJ54",
    "oldCode": "CHB-504"
  },
  {
    "code": "CHB-504",
    "subject": "Physical Chemistry III",
    "semester": 5,
    "year": "2016-17",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-504_PhysicalChemistryIII_SemV_2016-17.tex",
    "fileName": "CHB-504_PhysicalChemistryIII_SemV_2016-17.tex",
    "nepCode": "CHEMJ54",
    "oldCode": "CHB-504"
  },
  {
    "code": "CHB-504",
    "subject": "Physical Chemistry III",
    "semester": 5,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-504_PhysicalChemistryIII_SemV_2022-23.tex",
    "fileName": "CHB-504_PhysicalChemistryIII_SemV_2022-23.tex",
    "nepCode": "CHEMJ54",
    "oldCode": "CHB-504"
  },
  {
    "code": "CHB-601",
    "subject": "Analytical Chemistry I",
    "semester": 6,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-601_AnalyticalChemistryI_SemVI_2013-14.tex",
    "fileName": "CHB-601_AnalyticalChemistryI_SemVI_2013-14.tex",
    "nepCode": "CHEMJ61",
    "oldCode": "CHB-601"
  },
  {
    "code": "CHB-601",
    "subject": "Analytical Chemistry II",
    "semester": 6,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-601_AnalyticalChemistryII_SemVI_2022-23.tex",
    "fileName": "CHB-601_AnalyticalChemistryII_SemVI_2022-23.tex",
    "nepCode": "CHEMJ61",
    "oldCode": "CHB-601"
  },
  {
    "code": "CHB-608",
    "subject": "Atomic and Molecular Structure",
    "semester": 6,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-608_AtomicandMolecularStructure_SemVI_2013-14.tex",
    "fileName": "CHB-608_AtomicandMolecularStructure_SemVI_2013-14.tex",
    "nepCode": "CHEMJ85 / CHEMJ8R5",
    "oldCode": "CHB-605 / CHB-608"
  },
  {
    "code": "CHB-605",
    "subject": "Atomic and Molecular Structure",
    "semester": 6,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-605_AtomicandMolecularStructure_SemVI_2022-23.tex",
    "fileName": "CHB-605_AtomicandMolecularStructure_SemVI_2022-23.tex",
    "nepCode": "CHEMJ85 / CHEMJ8R5",
    "oldCode": "CHB-605 / CHB-608"
  },
  {
    "code": "CHB-602",
    "subject": "Inorganic Chemistry IV",
    "semester": 6,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-602_InorganicChemistryIV_SemVI_2013-14.tex",
    "fileName": "CHB-602_InorganicChemistryIV_SemVI_2013-14.tex",
    "nepCode": "CHEMJ62",
    "oldCode": "CHB-602"
  },
  {
    "code": "CHB-602",
    "subject": "Inorganic Chemistry IV",
    "semester": 6,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-602_InorganicChemistryIV_SemVI_2022-23.tex",
    "fileName": "CHB-602_InorganicChemistryIV_SemVI_2022-23.tex",
    "nepCode": "CHEMJ62",
    "oldCode": "CHB-602"
  },
  {
    "code": "CHB-603",
    "subject": "Organic Chemistry IV",
    "semester": 6,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-603_OrganicChemistryIV_SemVI_2013-14.tex",
    "fileName": "CHB-603_OrganicChemistryIV_SemVI_2013-14.tex",
    "nepCode": "CHEMJ63",
    "oldCode": "CHB-603"
  },
  {
    "code": "CHB-603",
    "subject": "Organic Chemistry V",
    "semester": 6,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-603_OrganicChemistryV_SemVI_2022-23.tex",
    "fileName": "CHB-603_OrganicChemistryV_SemVI_2022-23.tex",
    "nepCode": "CHEMJ63",
    "oldCode": "CHB-603"
  },
  {
    "code": "CHB-604",
    "subject": "Physical Chemistry IV",
    "semester": 6,
    "year": "2013-14",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-604_PhysicalChemistryIV_SemVI_2013-14.tex",
    "fileName": "CHB-604_PhysicalChemistryIV_SemVI_2013-14.tex",
    "nepCode": "CHEMJ64",
    "oldCode": "CHB-604"
  },
  {
    "code": "CHB-604",
    "subject": "Physical Chemistry IV",
    "semester": 6,
    "year": "2022-23",
    "department": "Chemistry",
    "filePath": "aaa/chemistry/tex_files/CHB-604_PhysicalChemistryIV_SemVI_2022-23.tex",
    "fileName": "CHB-604_PhysicalChemistryIV_SemVI_2022-23.tex",
    "nepCode": "CHEMJ64",
    "oldCode": "CHB-604"
  },
  {
    "code": "BSCU7A",
    "subject": "Ancillary Physics",
    "semester": 1,
    "year": "2016-17",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BSCU7A_AncillaryPhysics_SemI_2016-17.tex",
    "fileName": "BSCU7A_AncillaryPhysics_SemI_2016-17.tex",
    "nepCode": "PHYMN11",
    "oldCode": "BSCU7A"
  },
  {
    "code": "BPT-101",
    "subject": "Mechanics and Relativity",
    "semester": 1,
    "year": "2016-17",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-101_MechanicsandRelativity_SemI_2016-17.tex",
    "fileName": "BPT-101_MechanicsandRelativity_SemI_2016-17.tex",
    "nepCode": "PHYMJ11 / PHYMN11",
    "oldCode": "BPT-101"
  },
  {
    "code": "BPT-101",
    "subject": "Mechanics and Relativity",
    "semester": 1,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-101_MechanicsandRelativity_SemI_2022-23.tex",
    "fileName": "BPT-101_MechanicsandRelativity_SemI_2022-23.tex",
    "nepCode": "PHYMJ11 / PHYMN11",
    "oldCode": "BPT-101"
  },
  {
    "code": "BPT-101",
    "subject": "Mechanics and Relativity",
    "semester": 1,
    "year": "2023-24",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-101_MechanicsandRelativity_SemI_2023-24.tex",
    "fileName": "BPT-101_MechanicsandRelativity_SemI_2023-24.tex",
    "nepCode": "PHYMJ11 / PHYMN11",
    "oldCode": "BPT-101"
  },
  {
    "code": "BP-Anc-I",
    "subject": "Ancillary Physics- I",
    "semester": 2,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BP-Anc-I_AncillaryPhysics-I_SemII_2013-14.tex",
    "fileName": "BP-Anc-I_AncillaryPhysics-I_SemII_2013-14.tex",
    "nepCode": "PHYMN21",
    "oldCode": "BP-Anc-I"
  },
  {
    "code": "BPT-201",
    "subject": "Thermal Physics",
    "semester": 2,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-201_ThermalPhysics_SemII_2013-14.tex",
    "fileName": "BPT-201_ThermalPhysics_SemII_2013-14.tex",
    "nepCode": "PHYMJ21 / PHYMN21",
    "oldCode": "BPT-201"
  },
  {
    "code": "BPT-301",
    "subject": "Optics",
    "semester": 3,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-301_Optics_SemIII_2022-23.tex",
    "fileName": "BPT-301_Optics_SemIII_2022-23.tex",
    "nepCode": "PHYMJ31",
    "oldCode": "BPT-301"
  },
  {
    "code": "BPT-301",
    "subject": "Optics",
    "semester": 3,
    "year": "2023-24",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-301_Optics_SemIII_2023-24.tex",
    "fileName": "BPT-301_Optics_SemIII_2023-24.tex",
    "nepCode": "PHYMJ31",
    "oldCode": "BPT-301"
  },
  {
    "code": "PHYSICS",
    "subject": "Ancillary Physics- II",
    "semester": 4,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/PHYSICS_AncillaryPhysics-II_SemIV_2013-14.tex",
    "fileName": "PHYSICS_AncillaryPhysics-II_SemIV_2013-14.tex",
    "nepCode": "PHYMN41",
    "oldCode": "BSC-07A"
  },
  {
    "code": "BSC-07A",
    "subject": "Ancillary Physics- II",
    "semester": 4,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BSC-07A_AncillaryPhysics-II_SemIV_2022-23.tex",
    "fileName": "BSC-07A_AncillaryPhysics-II_SemIV_2022-23.tex",
    "nepCode": "PHYMN41",
    "oldCode": "BSC-07A"
  },
  {
    "code": "BSC-07A",
    "subject": "Ancillary Physics- II",
    "semester": 4,
    "year": "2023-24",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BSC-07A_AncillaryPhysics-II_SemIV_2023-24.tex",
    "fileName": "BSC-07A_AncillaryPhysics-II_SemIV_2023-24.tex",
    "nepCode": "PHYMN41",
    "oldCode": "BSC-07A"
  },
  {
    "code": "BPT-401",
    "subject": "Electromagnetic Theory and Basic Electronics Old",
    "semester": 4,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-401_ElectromagneticTheoryandBasicElectronicsOld_SemIV_2013-14.tex",
    "fileName": "BPT-401_ElectromagneticTheoryandBasicElectronicsOld_SemIV_2013-14.tex",
    "nepCode": "PHYMJ41 / PHYMN41",
    "oldCode": "BPT-401"
  },
  {
    "code": "BPT-401",
    "subject": "Electronics and Modern Physics",
    "semester": 4,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-401_ElectronicsandModernPhysics_SemIV_2013-14.tex",
    "fileName": "BPT-401_ElectronicsandModernPhysics_SemIV_2013-14.tex",
    "nepCode": "PHYMJ61",
    "oldCode": "BPT-401"
  },
  {
    "code": "BPT-401",
    "subject": "Electronics and Modern Physics",
    "semester": 4,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-401_ElectronicsandModernPhysics_SemIV_2022-23.tex",
    "fileName": "BPT-401_ElectronicsandModernPhysics_SemIV_2022-23.tex",
    "nepCode": "PHYMJ61",
    "oldCode": "BPT-401"
  },
  {
    "code": "BPT-401",
    "subject": "Electronics and Modern Physics",
    "semester": 4,
    "year": "2023-24",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-401_ElectronicsandModernPhysics_SemIV_2023-24.tex",
    "fileName": "BPT-401_ElectronicsandModernPhysics_SemIV_2023-24.tex",
    "nepCode": "PHYMJ61",
    "oldCode": "BPT-401"
  },
  {
    "code": "BPT-502",
    "subject": "Classical Mechanics",
    "semester": 5,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-502_ClassicalMechanics_SemV_2013-14.tex",
    "fileName": "BPT-502_ClassicalMechanics_SemV_2013-14.tex",
    "nepCode": "PHYMJ52",
    "oldCode": "BPT-502"
  },
  {
    "code": "BPT-502",
    "subject": "Classical Mechanics",
    "semester": 5,
    "year": "2016-17",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-502_ClassicalMechanics_SemV_2016-17.tex",
    "fileName": "BPT-502_ClassicalMechanics_SemV_2016-17.tex",
    "nepCode": "PHYMJ52",
    "oldCode": "BPT-502"
  },
  {
    "code": "BPT-502",
    "subject": "Classical Mechanics",
    "semester": 5,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-502_ClassicalMechanics_SemV_2022-23.tex",
    "fileName": "BPT-502_ClassicalMechanics_SemV_2022-23.tex",
    "nepCode": "PHYMJ52",
    "oldCode": "BPT-502"
  },
  {
    "code": "BPT-505",
    "subject": "Electromagnetic Theory",
    "semester": 5,
    "year": "2016-17",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-505_ElectromagneticTheory_SemV_2016-17.tex",
    "fileName": "BPT-505_ElectromagneticTheory_SemV_2016-17.tex",
    "nepCode": "PHYMJ41 / PHYMN41",
    "oldCode": "BPT-505"
  },
  {
    "code": "BPT-505",
    "subject": "Electromagnetic Theory",
    "semester": 5,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-505_ElectromagneticTheory_SemV_2022-23.tex",
    "fileName": "BPT-505_ElectromagneticTheory_SemV_2022-23.tex",
    "nepCode": "PHYMJ41 / PHYMN41",
    "oldCode": "BPT-505"
  },
  {
    "code": "BPT-504",
    "subject": "Electronic Devices and Circuits",
    "semester": 5,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-504_ElectronicDevicesandCircuits_SemV_2013-14.tex",
    "fileName": "BPT-504_ElectronicDevicesandCircuits_SemV_2013-14.tex",
    "nepCode": "PHYMJ32",
    "oldCode": "BPT-504"
  },
  {
    "code": "BPT-504",
    "subject": "Electronic Devices and Circuits",
    "semester": 5,
    "year": "2016-17",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-504_ElectronicDevicesandCircuits_SemV_2016-17.tex",
    "fileName": "BPT-504_ElectronicDevicesandCircuits_SemV_2016-17.tex",
    "nepCode": "PHYMJ32",
    "oldCode": "BPT-504"
  },
  {
    "code": "BPT-504",
    "subject": "Electronic Devices and Circuits",
    "semester": 5,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-504_ElectronicDevicesandCircuits_SemV_2022-23.tex",
    "fileName": "BPT-504_ElectronicDevicesandCircuits_SemV_2022-23.tex",
    "nepCode": "PHYMJ32",
    "oldCode": "BPT-504"
  },
  {
    "code": "BPT-501",
    "subject": "Mathematical Physics",
    "semester": 5,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-501_MathematicalPhysics_SemV_2013-14.tex",
    "fileName": "BPT-501_MathematicalPhysics_SemV_2013-14.tex",
    "nepCode": "PHYMJ42",
    "oldCode": "BPT-501"
  },
  {
    "code": "BPT-501",
    "subject": "Mathematical Physics",
    "semester": 5,
    "year": "2016-17",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-501_MathematicalPhysics_SemV_2016-17.tex",
    "fileName": "BPT-501_MathematicalPhysics_SemV_2016-17.tex",
    "nepCode": "PHYMJ42",
    "oldCode": "BPT-501"
  },
  {
    "code": "BPT-501",
    "subject": "Mathematical Physics",
    "semester": 5,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-501_MathematicalPhysics_SemV_2022-23.tex",
    "fileName": "BPT-501_MathematicalPhysics_SemV_2022-23.tex",
    "nepCode": "PHYMJ42",
    "oldCode": "BPT-501"
  },
  {
    "code": "BPT-503",
    "subject": "Quantum Mechanics",
    "semester": 5,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-503_QuantumMechanics_SemV_2013-14.tex",
    "fileName": "BPT-503_QuantumMechanics_SemV_2013-14.tex",
    "nepCode": "PHYMJ51",
    "oldCode": "BPT-503"
  },
  {
    "code": "BPT-503",
    "subject": "Quantum Mechanics",
    "semester": 5,
    "year": "2016-17",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-503_QuantumMechanics_SemV_2016-17.tex",
    "fileName": "BPT-503_QuantumMechanics_SemV_2016-17.tex",
    "nepCode": "PHYMJ51",
    "oldCode": "BPT-503"
  },
  {
    "code": "BPT-503",
    "subject": "Quantum Mechanics",
    "semester": 5,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-503_QuantumMechanics_SemV_2022-23.tex",
    "fileName": "BPT-503_QuantumMechanics_SemV_2022-23.tex",
    "nepCode": "PHYMJ51",
    "oldCode": "BPT-503"
  },
  {
    "code": "BPT-604",
    "subject": "Atomic Physics and Lasers",
    "semester": 6,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-604_AtomicPhysicsandLasers_SemVI_2013-14.tex",
    "fileName": "BPT-604_AtomicPhysicsandLasers_SemVI_2013-14.tex",
    "nepCode": "PHYMJ63",
    "oldCode": "BPT-604"
  },
  {
    "code": "BPT-604",
    "subject": "Atomic Physics and Lasers",
    "semester": 6,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-604_AtomicPhysicsandLasers_SemVI_2022-23.tex",
    "fileName": "BPT-604_AtomicPhysicsandLasers_SemVI_2022-23.tex",
    "nepCode": "PHYMJ63",
    "oldCode": "BPT-604"
  },
  {
    "code": "BPE-602",
    "subject": "Elementary Nanoscience",
    "semester": 6,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPE-602_ElementaryNanoscience_SemVI_2013-14.tex",
    "fileName": "BPE-602_ElementaryNanoscience_SemVI_2013-14.tex",
    "nepCode": "PHYMJ75",
    "oldCode": "BPE-602"
  },
  {
    "code": "BPE-602",
    "subject": "Elementary Nanoscience",
    "semester": 6,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPE-602_ElementaryNanoscience_SemVI_2022-23.tex",
    "fileName": "BPE-602_ElementaryNanoscience_SemVI_2022-23.tex",
    "nepCode": "PHYMJ75",
    "oldCode": "BPE-602"
  },
  {
    "code": "BPT-603",
    "subject": "Elements of Nuclear Physics",
    "semester": 6,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-603_ElementsofNuclearPhysics_SemVI_2013-14.tex",
    "fileName": "BPT-603_ElementsofNuclearPhysics_SemVI_2013-14.tex",
    "nepCode": "PHYMJ64",
    "oldCode": "BPT-603"
  },
  {
    "code": "BPT-603",
    "subject": "Elements of Nuclear Physics",
    "semester": 6,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-603_ElementsofNuclearPhysics_SemVI_2022-23.tex",
    "fileName": "BPT-603_ElementsofNuclearPhysics_SemVI_2022-23.tex",
    "nepCode": "PHYMJ64",
    "oldCode": "BPT-603"
  },
  {
    "code": "BPT-602",
    "subject": "Solid State Physics",
    "semester": 6,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-602_SolidStatePhysics_SemVI_2013-14.tex",
    "fileName": "BPT-602_SolidStatePhysics_SemVI_2013-14.tex",
    "nepCode": "PHYMJ62",
    "oldCode": "BPT-602"
  },
  {
    "code": "BPT-602",
    "subject": "Solid State Physics",
    "semester": 6,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-602_SolidStatePhysics_SemVI_2022-23.tex",
    "fileName": "BPT-602_SolidStatePhysics_SemVI_2022-23.tex",
    "nepCode": "PHYMJ62",
    "oldCode": "BPT-602"
  },
  {
    "code": "BPT-601",
    "subject": "Statistical Mechanics",
    "semester": 6,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-601_StatisticalMechanics_SemVI_2013-14.tex",
    "fileName": "BPT-601_StatisticalMechanics_SemVI_2013-14.tex",
    "nepCode": "PHYMJ53",
    "oldCode": "BPT-601"
  },
  {
    "code": "BPT-601",
    "subject": "Statistical Mechanics",
    "semester": 6,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPT-601_StatisticalMechanics_SemVI_2022-23.tex",
    "fileName": "BPT-601_StatisticalMechanics_SemVI_2022-23.tex",
    "nepCode": "PHYMJ53",
    "oldCode": "BPT-601"
  },
  {
    "code": "BPE-601",
    "subject": "Topics in Modern Physics",
    "semester": 6,
    "year": "2013-14",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPE-601_TopicsinModernPhysics_SemVI_2013-14.tex",
    "fileName": "BPE-601_TopicsinModernPhysics_SemVI_2013-14.tex",
    "nepCode": "PHYMJ63",
    "oldCode": "BPE-601"
  },
  {
    "code": "BPE-601",
    "subject": "Topics in Modern Physics",
    "semester": 6,
    "year": "2022-23",
    "department": "Physics",
    "filePath": "aaa/PHYSICS OUT/BPE-601_TopicsinModernPhysics_SemVI_2022-23.tex",
    "fileName": "BPE-601_TopicsinModernPhysics_SemVI_2022-23.tex",
    "nepCode": "PHYMJ63",
    "oldCode": "BPE-601"
  }
];
